// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertCalculation = `-- name: UpsertCalculation :batchexec
INSERT INTO carbon.calculations (tenant_id, project_id, provider, region_id, service_name, service_category, method, period_start, period_end,
    energy_kwh, intensity_g_per_kwh, embodied_g, carbon_kg_co2e, functional_units, sci_score, methodology_version)
VALUES ($1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16)
ON CONFLICT (tenant_id, project_id, provider, service_name, region_id, method, methodology_version, period_start)
DO UPDATE SET energy_kwh = EXCLUDED.energy_kwh, intensity_g_per_kwh = EXCLUDED.intensity_g_per_kwh, embodied_g = EXCLUDED.embodied_g,
              carbon_kg_co2e = EXCLUDED.carbon_kg_co2e, functional_units = EXCLUDED.functional_units, sci_score = EXCLUDED.sci_score,
              period_end = EXCLUDED.period_end, calculated_at = now()
`

type UpsertCalculationBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCalculationParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          string    `json:"project_id"`
	Provider           string    `json:"provider"`
	RegionID           string    `json:"region_id"`
	ServiceName        string    `json:"service_name"`
	ServiceCategory    string    `json:"service_category"`
	Method             string    `json:"method"`
	PeriodStart        time.Time `json:"period_start"`
	PeriodEnd          time.Time `json:"period_end"`
	EnergyKwh          float64   `json:"energy_kwh"`
	IntensityGPerKwh   float64   `json:"intensity_g_per_kwh"`
	EmbodiedG          float64   `json:"embodied_g"`
	CarbonKgCo2e       float64   `json:"carbon_kg_co2e"`
	FunctionalUnits    *float64  `json:"functional_units"`
	SciScore           *float64  `json:"sci_score"`
	MethodologyVersion string    `json:"methodology_version"`
}

func (q *Queries) UpsertCalculation(ctx context.Context, arg []UpsertCalculationParams) *UpsertCalculationBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.ProjectID,
			a.Provider,
			a.RegionID,
			a.ServiceName,
			a.ServiceCategory,
			a.Method,
			a.PeriodStart,
			a.PeriodEnd,
			a.EnergyKwh,
			a.IntensityGPerKwh,
			a.EmbodiedG,
			a.CarbonKgCo2e,
			a.FunctionalUnits,
			a.SciScore,
			a.MethodologyVersion,
		}
		batch.Queue(upsertCalculation, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCalculationBatchResults{br, len(arg), false}
}

func (b *UpsertCalculationBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertCalculationBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
