// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carbon.sql

package db

import (
	"context"
	"time"
)

const carbonTotals = `-- name: CarbonTotals :one
WITH daily AS (
  SELECT project_id, date_trunc('day', period_start) AS day,
         sum(energy_kwh) AS energy, sum(carbon_kg_co2e) AS kg, max(functional_units) AS r, count(*) AS n
  FROM carbon.calculations
  WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
    AND methodology_version = $3
    AND period_start >= $4 AND period_start < $5
  GROUP BY project_id, day
)
SELECT COALESCE(sum(energy), 0)::float8 AS energy_kwh,
       COALESCE(sum(kg), 0)::float8 AS carbon_kg_co2e,
       COALESCE(sum(n), 0)::bigint AS row_count,
       COALESCE(sum(kg * 1000) FILTER (WHERE r IS NOT NULL), 0)::float8 AS sci_grams,
       COALESCE(sum(r), 0)::float8 AS sci_units,
       count(DISTINCT day)::int AS days
FROM daily
`

type CarbonTotalsParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type CarbonTotalsRow struct {
	EnergyKwh    float64 `json:"energy_kwh"`
	CarbonKgCo2e float64 `json:"carbon_kg_co2e"`
	RowCount     int64   `json:"row_count"`
	SciGrams     float64 `json:"sci_grams"`
	SciUnits     float64 `json:"sci_units"`
	Days         int32   `json:"days"`
}

// SCI over a window = total carbon / total functional units, counting R once per (project, day) and
// only on days where R was reported (never extrapolated). Per-row sci_score is that row's share of its day's SCI.
func (q *Queries) CarbonTotals(ctx context.Context, arg CarbonTotalsParams) (CarbonTotalsRow, error) {
	row := q.db.QueryRow(ctx, carbonTotals,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	var i CarbonTotalsRow
	err := row.Scan(
		&i.EnergyKwh,
		&i.CarbonKgCo2e,
		&i.RowCount,
		&i.SciGrams,
		&i.SciUnits,
		&i.Days,
	)
	return i, err
}

const carbonTrend = `-- name: CarbonTrend :many
SELECT date_trunc('day', period_start)::timestamptz AS day, sum(carbon_kg_co2e)::float8 AS carbon_kg_co2e
FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
GROUP BY day ORDER BY day
`

type CarbonTrendParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type CarbonTrendRow struct {
	Day          time.Time `json:"day"`
	CarbonKgCo2e float64   `json:"carbon_kg_co2e"`
}

func (q *Queries) CarbonTrend(ctx context.Context, arg CarbonTrendParams) ([]CarbonTrendRow, error) {
	rows, err := q.db.Query(ctx, carbonTrend,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CarbonTrendRow{}
	for rows.Next() {
		var i CarbonTrendRow
		if err := rows.Scan(&i.Day, &i.CarbonKgCo2e); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const intensityAt = `-- name: IntensityAt :one
SELECT g_co2e_per_kwh FROM carbon.grid_intensity
WHERE region_id = $1 AND NOT is_forecast AND ts <= $2
ORDER BY ts DESC LIMIT 1
`

type IntensityAtParams struct {
	RegionID string    `json:"region_id"`
	Ts       time.Time `json:"ts"`
}

// Latest stored (non-forecast) reading at or before ts for a region.
func (q *Queries) IntensityAt(ctx context.Context, arg IntensityAtParams) (float64, error) {
	row := q.db.QueryRow(ctx, intensityAt, arg.RegionID, arg.Ts)
	var g_co2e_per_kwh float64
	err := row.Scan(&g_co2e_per_kwh)
	return g_co2e_per_kwh, err
}

const latestIntensity = `-- name: LatestIntensity :one
SELECT g_co2e_per_kwh FROM carbon.grid_intensity
WHERE region_id = $1 AND NOT is_forecast ORDER BY ts DESC LIMIT 1
`

func (q *Queries) LatestIntensity(ctx context.Context, regionID string) (float64, error) {
	row := q.db.QueryRow(ctx, latestIntensity, regionID)
	var g_co2e_per_kwh float64
	err := row.Scan(&g_co2e_per_kwh)
	return g_co2e_per_kwh, err
}

const saveGridIntensity = `-- name: SaveGridIntensity :exec
INSERT INTO carbon.grid_intensity (provider, region_id, ts, g_co2e_per_kwh, is_forecast)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type SaveGridIntensityParams struct {
	Provider    string    `json:"provider"`
	RegionID    string    `json:"region_id"`
	Ts          time.Time `json:"ts"`
	GCo2ePerKwh float64   `json:"g_co2e_per_kwh"`
	IsForecast  bool      `json:"is_forecast"`
}

func (q *Queries) SaveGridIntensity(ctx context.Context, arg SaveGridIntensityParams) error {
	_, err := q.db.Exec(ctx, saveGridIntensity,
		arg.Provider,
		arg.RegionID,
		arg.Ts,
		arg.GCo2ePerKwh,
		arg.IsForecast,
	)
	return err
}
