// Package repository is the PostgreSQL adapter for cloud connections (queries generated by sqlc).
package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/cloudaccounts/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/cloudaccounts/repository/db"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/audit"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
)

type Postgres struct{ Pool *pgxpool.Pool }

func toConn(r db.CloudaccountsConnection) domain.Connection {
	return domain.Connection{ID: r.ID, TenantID: r.TenantID, ProjectID: r.ProjectID, Provider: domain.ProviderType(r.Provider),
		AccountRef: r.AccountRef, CredentialRef: r.CredentialRef, ExternalID: r.ExternalID, SyncStatus: domain.SyncStatus(r.SyncStatus),
		LastError: r.LastError, LastSyncAt: r.LastSyncAt, SyncedThrough: r.SyncedThrough}
}

func (r Postgres) List(ctx context.Context, tenantID string) ([]domain.Connection, error) {
	out := []domain.Connection{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListConnections(ctx, tenantID)
		for _, x := range rows {
			out = append(out, toConn(x))
		}
		return err
	})
	return out, err
}

func (r Postgres) Get(ctx context.Context, tenantID, id string) (c domain.Connection, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		row, err := db.New(tx).GetConnection(ctx, db.GetConnectionParams{TenantID: tenantID, ID: id})
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		c = toConn(row)
		return err
	})
	return
}

func (r Postgres) Create(ctx context.Context, c domain.Connection) (domain.Connection, error) {
	err := database.WithTenantTx(ctx, r.Pool, c.TenantID, func(tx pgx.Tx) error {
		row, err := db.New(tx).CreateConnection(ctx, db.CreateConnectionParams{TenantID: c.TenantID, ProjectID: c.ProjectID,
			Provider: string(c.Provider), AccountRef: c.AccountRef, CredentialRef: c.CredentialRef, ExternalID: c.ExternalID})
		if err != nil {
			return err
		}
		c = toConn(row)
		return audit.Record(ctx, tx, "cloud_connection.created", "connection:"+c.ID, map[string]any{"provider": c.Provider, "account": c.AccountRef})
	})
	if database.IsUniqueViolation(err) {
		return domain.Connection{}, domain.ErrDuplicate
	}
	return c, err
}

func (r Postgres) Delete(ctx context.Context, tenantID, id string) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		n, err := db.New(tx).DeleteConnection(ctx, db.DeleteConnectionParams{TenantID: tenantID, ID: id})
		if err != nil {
			return err
		}
		if n == 0 {
			return domain.ErrNotFound
		}
		return audit.Record(ctx, tx, "cloud_connection.deleted", "connection:"+id, nil)
	})
}

func (r Postgres) SetStatus(ctx context.Context, tenantID, id string, status domain.SyncStatus, lastError *string) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		return db.New(tx).SetConnectionStatus(ctx, db.SetConnectionStatusParams{TenantID: tenantID, ID: id, Status: string(status), LastError: lastError})
	})
}

func (r Postgres) StartRun(ctx context.Context, tenantID, connectionID string) (id string, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		id, err = db.New(tx).StartSyncRun(ctx, db.StartSyncRunParams{TenantID: tenantID, ConnectionID: connectionID})
		return err
	})
	return
}

func (r Postgres) FinishRun(ctx context.Context, tenantID, runID string, ok bool, records int, errMsg *string) error {
	status := "failed"
	if ok {
		status = "succeeded"
	}
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		return db.New(tx).FinishSyncRun(ctx, db.FinishSyncRunParams{TenantID: tenantID, ID: runID, Status: status, Records: int32(records), Error: errMsg}) //nolint:gosec // record counts are far below int32 range
	})
}

// MarkSynced records a successful sync and writes the user-visible "cloud_sync.completed" audit entry.
func (r Postgres) MarkSynced(ctx context.Context, tenantID, id string, through time.Time, records int) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		if err := db.New(tx).MarkConnectionSynced(ctx, db.MarkConnectionSyncedParams{TenantID: tenantID, ID: id, SyncedThrough: &through}); err != nil {
			return err
		}
		return audit.Record(audit.WithTenant(ctx, tenantID), tx, "cloud_sync.completed", "connection:"+id, map[string]any{"records": records})
	})
}

func (r Postgres) ListRuns(ctx context.Context, tenantID, connectionID string) ([]domain.SyncRun, error) {
	out := []domain.SyncRun{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListSyncRuns(ctx, db.ListSyncRunsParams{TenantID: tenantID, ConnectionID: connectionID})
		for _, x := range rows {
			out = append(out, domain.SyncRun{ID: x.ID, StartedAt: x.StartedAt, FinishedAt: x.FinishedAt, Status: x.Status, Records: int(x.Records), Error: x.Error})
		}
		return err
	})
	return out, err
}

// ListForSync lists every syncable connection across tenants (SECURITY DEFINER function; scheduler only).
func (r Postgres) ListForSync(ctx context.Context) ([]domain.JobRef, error) {
	rows, err := r.Pool.Query(ctx, `SELECT tenant_id::text, project_id::text, connection_id::text FROM cloudaccounts.list_connections_for_sync()`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []domain.JobRef
	for rows.Next() {
		var j domain.JobRef
		if err := rows.Scan(&j.TenantID, &j.ProjectID, &j.ConnectionID); err != nil {
			return nil, err
		}
		out = append(out, j)
	}
	return out, rows.Err()
}

func (r Postgres) Audit(ctx context.Context, tenantID, action, connectionID string, meta map[string]any) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		return audit.Record(ctx, tx, action, "connection:"+connectionID, meta)
	})
}
