// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"
)

const dashboardActivity = `-- name: DashboardActivity :many
SELECT id, action, target, created_at FROM audit.audit_logs
WHERE tenant_id = $1 AND action = ANY($2::text[])
ORDER BY created_at DESC LIMIT $3
`

type DashboardActivityParams struct {
	TenantID string   `json:"tenant_id"`
	Actions  []string `json:"actions"`
	RowLimit int32    `json:"row_limit"`
}

type DashboardActivityRow struct {
	ID        int64     `json:"id"`
	Action    string    `json:"action"`
	Target    string    `json:"target"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) DashboardActivity(ctx context.Context, arg DashboardActivityParams) ([]DashboardActivityRow, error) {
	rows, err := q.db.Query(ctx, dashboardActivity, arg.TenantID, arg.Actions, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardActivityRow{}
	for rows.Next() {
		var i DashboardActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Target,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardProviders = `-- name: DashboardProviders :many
SELECT provider, sum(carbon_kg_co2e)::float8 AS carbon_kg_co2e FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
GROUP BY provider HAVING sum(carbon_kg_co2e) > 0 ORDER BY 2 DESC
`

type DashboardProvidersParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type DashboardProvidersRow struct {
	Provider     string  `json:"provider"`
	CarbonKgCo2e float64 `json:"carbon_kg_co2e"`
}

func (q *Queries) DashboardProviders(ctx context.Context, arg DashboardProvidersParams) ([]DashboardProvidersRow, error) {
	rows, err := q.db.Query(ctx, dashboardProviders,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardProvidersRow{}
	for rows.Next() {
		var i DashboardProvidersRow
		if err := rows.Scan(&i.Provider, &i.CarbonKgCo2e); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRegions = `-- name: DashboardRegions :many
WITH latest AS (
  SELECT DISTINCT ON (region_id) region_id, g_co2e_per_kwh AS g, ts FROM carbon.grid_intensity
  WHERE provider = 'electricitymaps' AND NOT is_forecast ORDER BY region_id, ts DESC
), prev AS (
  SELECT DISTINCT ON (gi.region_id) gi.region_id, gi.g_co2e_per_kwh AS g FROM carbon.grid_intensity gi
  JOIN latest l ON l.region_id = gi.region_id AND gi.ts <= l.ts - interval '24 hours'
  WHERE gi.provider = 'electricitymaps' AND NOT gi.is_forecast ORDER BY gi.region_id, gi.ts DESC
)
SELECT l.region_id, l.g::float8 AS g_per_kwh, l.ts AS at, p.g AS prev_g_per_kwh
FROM latest l LEFT JOIN prev p USING (region_id) ORDER BY l.g
`

type DashboardRegionsRow struct {
	RegionID    string    `json:"region_id"`
	GPerKwh     float64   `json:"g_per_kwh"`
	At          time.Time `json:"at"`
	PrevGPerKwh *float64  `json:"prev_g_per_kwh"`
}

// Reference data (no tenant): latest reading per region and the one >= 24h older, for the change column.
func (q *Queries) DashboardRegions(ctx context.Context) ([]DashboardRegionsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRegionsRow{}
	for rows.Next() {
		var i DashboardRegionsRow
		if err := rows.Scan(
			&i.RegionID,
			&i.GPerKwh,
			&i.At,
			&i.PrevGPerKwh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardServiceCarbon = `-- name: DashboardServiceCarbon :many
SELECT service_name, service_category, date_trunc('day', period_start)::timestamptz AS day, sum(carbon_kg_co2e)::float8 AS carbon_kg_co2e
FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
  AND ($6::text = '' OR service_category = $6::text)
GROUP BY 1, 2, 3 ORDER BY 3
`

type DashboardServiceCarbonParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
	Category           string    `json:"category"`
}

type DashboardServiceCarbonRow struct {
	ServiceName     string    `json:"service_name"`
	ServiceCategory string    `json:"service_category"`
	Day             time.Time `json:"day"`
	CarbonKgCo2e    float64   `json:"carbon_kg_co2e"`
}

func (q *Queries) DashboardServiceCarbon(ctx context.Context, arg DashboardServiceCarbonParams) ([]DashboardServiceCarbonRow, error) {
	rows, err := q.db.Query(ctx, dashboardServiceCarbon,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardServiceCarbonRow{}
	for rows.Next() {
		var i DashboardServiceCarbonRow
		if err := rows.Scan(
			&i.ServiceName,
			&i.ServiceCategory,
			&i.Day,
			&i.CarbonKgCo2e,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardServiceCost = `-- name: DashboardServiceCost :many
SELECT service_name, service_category, sum(billed_cost)::float8 AS cost FROM usage.usage_records
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND recorded_at >= $3 AND recorded_at < $4
  AND ($5::text = '' OR service_category = $5::text)
GROUP BY 1, 2
`

type DashboardServiceCostParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
	Category  string    `json:"category"`
}

type DashboardServiceCostRow struct {
	ServiceName     string  `json:"service_name"`
	ServiceCategory string  `json:"service_category"`
	Cost            float64 `json:"cost"`
}

func (q *Queries) DashboardServiceCost(ctx context.Context, arg DashboardServiceCostParams) ([]DashboardServiceCostRow, error) {
	rows, err := q.db.Query(ctx, dashboardServiceCost,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardServiceCostRow{}
	for rows.Next() {
		var i DashboardServiceCostRow
		if err := rows.Scan(&i.ServiceName, &i.ServiceCategory, &i.Cost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTrend = `-- name: DashboardTrend :many
WITH cost_d AS (
  SELECT date_trunc('day', u.recorded_at) AS d, sum(u.billed_cost) AS cost FROM usage.usage_records u
  WHERE u.tenant_id = $1 AND ($2::uuid IS NULL OR u.project_id = $2)
    AND u.recorded_at >= $3 AND u.recorded_at < $4 GROUP BY 1
), carbon_d AS (
  SELECT date_trunc('day', x.period_start) AS d, sum(x.carbon_kg_co2e) AS co2e FROM carbon.calculations x
  WHERE x.tenant_id = $1 AND ($2::uuid IS NULL OR x.project_id = $2)
    AND x.methodology_version = $5
    AND x.period_start >= $3 AND x.period_start < $4 GROUP BY 1
)
SELECT COALESCE(cost_d.d, carbon_d.d)::timestamptz AS day, COALESCE(cost_d.cost, 0)::float8 AS cost, COALESCE(carbon_d.co2e, 0)::float8 AS carbon_kg_co2e
FROM cost_d FULL JOIN carbon_d ON cost_d.d = carbon_d.d ORDER BY 1
`

type DashboardTrendParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
	MethodologyVersion string    `json:"methodology_version"`
}

type DashboardTrendRow struct {
	Day          time.Time `json:"day"`
	Cost         float64   `json:"cost"`
	CarbonKgCo2e float64   `json:"carbon_kg_co2e"`
}

func (q *Queries) DashboardTrend(ctx context.Context, arg DashboardTrendParams) ([]DashboardTrendRow, error) {
	rows, err := q.db.Query(ctx, dashboardTrend,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
		arg.MethodologyVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardTrendRow{}
	for rows.Next() {
		var i DashboardTrendRow
		if err := rows.Scan(&i.Day, &i.Cost, &i.CarbonKgCo2e); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
