// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"
)

const getReport = `-- name: GetReport :one
SELECT id, tenant_id, project_id, kind, format, period_start, period_end, status, object_key, error, requested_by, created_at, completed_at
FROM reports.reports WHERE tenant_id = $1 AND id = $2
`

type GetReportParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (ReportsReport, error) {
	row := q.db.QueryRow(ctx, getReport, arg.TenantID, arg.ID)
	var i ReportsReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Kind,
		&i.Format,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.ObjectKey,
		&i.Error,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports.reports (tenant_id, project_id, kind, format, period_start, period_end, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, project_id, kind, format, period_start, period_end, status, object_key, error, requested_by, created_at, completed_at
`

type InsertReportParams struct {
	TenantID    string    `json:"tenant_id"`
	ProjectID   *string   `json:"project_id"`
	Kind        string    `json:"kind"`
	Format      string    `json:"format"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	RequestedBy string    `json:"requested_by"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (ReportsReport, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.TenantID,
		arg.ProjectID,
		arg.Kind,
		arg.Format,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RequestedBy,
	)
	var i ReportsReport
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Kind,
		&i.Format,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.ObjectKey,
		&i.Error,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, tenant_id, project_id, kind, format, period_start, period_end, status, object_key, error, requested_by, created_at, completed_at
FROM reports.reports WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListReports(ctx context.Context, tenantID string) ([]ReportsReport, error) {
	rows, err := q.db.Query(ctx, listReports, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportsReport{}
	for rows.Next() {
		var i ReportsReport
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Kind,
			&i.Format,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.ObjectKey,
			&i.Error,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCarbonDaily = `-- name: ReportCarbonDaily :many
SELECT date_trunc('day', period_start)::timestamptz AS day, provider, service_name, region_id, method,
       sum(energy_kwh)::float8 AS energy_kwh, sum(carbon_kg_co2e)::float8 AS carbon_kg_co2e, methodology_version
FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND period_start >= $3 AND period_start < $4
GROUP BY day, provider, service_name, region_id, method, methodology_version ORDER BY day, service_name
`

type ReportCarbonDailyParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type ReportCarbonDailyRow struct {
	Day                time.Time `json:"day"`
	Provider           string    `json:"provider"`
	ServiceName        string    `json:"service_name"`
	RegionID           string    `json:"region_id"`
	Method             string    `json:"method"`
	EnergyKwh          float64   `json:"energy_kwh"`
	CarbonKgCo2e       float64   `json:"carbon_kg_co2e"`
	MethodologyVersion string    `json:"methodology_version"`
}

func (q *Queries) ReportCarbonDaily(ctx context.Context, arg ReportCarbonDailyParams) ([]ReportCarbonDailyRow, error) {
	rows, err := q.db.Query(ctx, reportCarbonDaily,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCarbonDailyRow{}
	for rows.Next() {
		var i ReportCarbonDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Provider,
			&i.ServiceName,
			&i.RegionID,
			&i.Method,
			&i.EnergyKwh,
			&i.CarbonKgCo2e,
			&i.MethodologyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCostDaily = `-- name: ReportCostDaily :many
SELECT date_trunc('day', recorded_at)::timestamptz AS day, provider, service_name, service_category, region_id,
       sum(billed_cost)::float8 AS billed_cost, sum(effective_cost)::float8 AS effective_cost, currency::text AS currency
FROM usage.usage_records
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND recorded_at >= $3 AND recorded_at < $4
GROUP BY day, provider, service_name, service_category, region_id, currency ORDER BY day, service_name
`

type ReportCostDailyParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type ReportCostDailyRow struct {
	Day             time.Time `json:"day"`
	Provider        string    `json:"provider"`
	ServiceName     string    `json:"service_name"`
	ServiceCategory string    `json:"service_category"`
	RegionID        string    `json:"region_id"`
	BilledCost      float64   `json:"billed_cost"`
	EffectiveCost   float64   `json:"effective_cost"`
	Currency        string    `json:"currency"`
}

func (q *Queries) ReportCostDaily(ctx context.Context, arg ReportCostDailyParams) ([]ReportCostDailyRow, error) {
	rows, err := q.db.Query(ctx, reportCostDaily,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCostDailyRow{}
	for rows.Next() {
		var i ReportCostDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Provider,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.RegionID,
			&i.BilledCost,
			&i.EffectiveCost,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSCIDaily = `-- name: ReportSCIDaily :many
SELECT p.name AS project, p.functional_unit, date_trunc('day', c.period_start)::timestamptz AS day,
       sum(c.carbon_kg_co2e)::float8 AS carbon_kg_co2e, max(c.functional_units)::float8 AS functional_units,
       c.methodology_version
FROM carbon.calculations c JOIN projects.projects p ON p.id = c.project_id AND p.tenant_id = c.tenant_id
WHERE c.tenant_id = $1 AND ($2::uuid IS NULL OR c.project_id = $2)
  AND c.period_start >= $3 AND c.period_start < $4
GROUP BY p.name, p.functional_unit, day, c.methodology_version ORDER BY p.name, day
`

type ReportSCIDailyParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type ReportSCIDailyRow struct {
	Project            string    `json:"project"`
	FunctionalUnit     string    `json:"functional_unit"`
	Day                time.Time `json:"day"`
	CarbonKgCo2e       float64   `json:"carbon_kg_co2e"`
	FunctionalUnits    float64   `json:"functional_units"`
	MethodologyVersion string    `json:"methodology_version"`
}

func (q *Queries) ReportSCIDaily(ctx context.Context, arg ReportSCIDailyParams) ([]ReportSCIDailyRow, error) {
	rows, err := q.db.Query(ctx, reportSCIDaily,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSCIDailyRow{}
	for rows.Next() {
		var i ReportSCIDailyRow
		if err := rows.Scan(
			&i.Project,
			&i.FunctionalUnit,
			&i.Day,
			&i.CarbonKgCo2e,
			&i.FunctionalUnits,
			&i.MethodologyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSustainabilityByMethod = `-- name: ReportSustainabilityByMethod :many
SELECT method, sum(energy_kwh)::float8 AS energy_kwh, sum(carbon_kg_co2e)::float8 AS carbon_kg
FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
GROUP BY method ORDER BY method
`

type ReportSustainabilityByMethodParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type ReportSustainabilityByMethodRow struct {
	Method    string  `json:"method"`
	EnergyKwh float64 `json:"energy_kwh"`
	CarbonKg  float64 `json:"carbon_kg"`
}

func (q *Queries) ReportSustainabilityByMethod(ctx context.Context, arg ReportSustainabilityByMethodParams) ([]ReportSustainabilityByMethodRow, error) {
	rows, err := q.db.Query(ctx, reportSustainabilityByMethod,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSustainabilityByMethodRow{}
	for rows.Next() {
		var i ReportSustainabilityByMethodRow
		if err := rows.Scan(&i.Method, &i.EnergyKwh, &i.CarbonKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSustainabilityRecommendations = `-- name: ReportSustainabilityRecommendations :many
SELECT status, count(*)::int AS n, COALESCE(sum(carbon_reduction_kg_month), 0)::float8 AS kg_month
FROM recommendations.recommendations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND created_at < $3
GROUP BY status ORDER BY status
`

type ReportSustainabilityRecommendationsParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	ToTs      time.Time `json:"to_ts"`
}

type ReportSustainabilityRecommendationsRow struct {
	Status  string  `json:"status"`
	N       int32   `json:"n"`
	KgMonth float64 `json:"kg_month"`
}

// Recommendations created up to the end of the window, by status: what is still open and what was done.
func (q *Queries) ReportSustainabilityRecommendations(ctx context.Context, arg ReportSustainabilityRecommendationsParams) ([]ReportSustainabilityRecommendationsRow, error) {
	rows, err := q.db.Query(ctx, reportSustainabilityRecommendations, arg.TenantID, arg.ProjectID, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSustainabilityRecommendationsRow{}
	for rows.Next() {
		var i ReportSustainabilityRecommendationsRow
		if err := rows.Scan(&i.Status, &i.N, &i.KgMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSustainabilityTopRegions = `-- name: ReportSustainabilityTopRegions :many
SELECT region_id, sum(carbon_kg_co2e)::float8 AS carbon_kg
FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
GROUP BY region_id ORDER BY carbon_kg DESC, region_id LIMIT 10
`

type ReportSustainabilityTopRegionsParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type ReportSustainabilityTopRegionsRow struct {
	RegionID string  `json:"region_id"`
	CarbonKg float64 `json:"carbon_kg"`
}

func (q *Queries) ReportSustainabilityTopRegions(ctx context.Context, arg ReportSustainabilityTopRegionsParams) ([]ReportSustainabilityTopRegionsRow, error) {
	rows, err := q.db.Query(ctx, reportSustainabilityTopRegions,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSustainabilityTopRegionsRow{}
	for rows.Next() {
		var i ReportSustainabilityTopRegionsRow
		if err := rows.Scan(&i.RegionID, &i.CarbonKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportSustainabilityTopServices = `-- name: ReportSustainabilityTopServices :many
SELECT provider, service_name, sum(carbon_kg_co2e)::float8 AS carbon_kg
FROM carbon.calculations
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
GROUP BY provider, service_name ORDER BY carbon_kg DESC, service_name LIMIT 10
`

type ReportSustainabilityTopServicesParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          *string   `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type ReportSustainabilityTopServicesRow struct {
	Provider    string  `json:"provider"`
	ServiceName string  `json:"service_name"`
	CarbonKg    float64 `json:"carbon_kg"`
}

func (q *Queries) ReportSustainabilityTopServices(ctx context.Context, arg ReportSustainabilityTopServicesParams) ([]ReportSustainabilityTopServicesRow, error) {
	rows, err := q.db.Query(ctx, reportSustainabilityTopServices,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportSustainabilityTopServicesRow{}
	for rows.Next() {
		var i ReportSustainabilityTopServicesRow
		if err := rows.Scan(&i.Provider, &i.ServiceName, &i.CarbonKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReportFailed = `-- name: SetReportFailed :exec
UPDATE reports.reports SET status = 'failed', error = $1, completed_at = now()
WHERE tenant_id = $2 AND id = $3
`

type SetReportFailedParams struct {
	Error    *string `json:"error"`
	TenantID string  `json:"tenant_id"`
	ID       string  `json:"id"`
}

func (q *Queries) SetReportFailed(ctx context.Context, arg SetReportFailedParams) error {
	_, err := q.db.Exec(ctx, setReportFailed, arg.Error, arg.TenantID, arg.ID)
	return err
}

const setReportReady = `-- name: SetReportReady :exec
UPDATE reports.reports SET status = 'ready', object_key = $1, error = NULL, completed_at = now()
WHERE tenant_id = $2 AND id = $3
`

type SetReportReadyParams struct {
	ObjectKey *string `json:"object_key"`
	TenantID  string  `json:"tenant_id"`
	ID        string  `json:"id"`
}

func (q *Queries) SetReportReady(ctx context.Context, arg SetReportReadyParams) error {
	_, err := q.db.Exec(ctx, setReportReady, arg.ObjectKey, arg.TenantID, arg.ID)
	return err
}
