// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finops.sql

package db

import (
	"context"
	"time"
)

const anomalies = `-- name: Anomalies :many
WITH d AS (
  SELECT date_trunc('day', recorded_at)::date AS day, sum(billed_cost)::float8 AS cost
  FROM usage.usage_records
  WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
    AND recorded_at >= $3 AND recorded_at < $4
  GROUP BY 1
), s AS (
  SELECT day, cost,
         avg(cost) OVER w AS mean, stddev_samp(cost) OVER w AS sd, count(*) OVER w AS n
  FROM d WINDOW w AS (ORDER BY day ROWS BETWEEN 14 PRECEDING AND 1 PRECEDING)
)
SELECT day::timestamptz AS day, cost, mean::float8 AS mean, sd::float8 AS stddev
FROM s WHERE n >= 7 AND sd > 0 AND cost > mean + 3 * sd ORDER BY day DESC LIMIT 20
`

type AnomaliesParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type AnomaliesRow struct {
	Day    time.Time `json:"day"`
	Cost   float64   `json:"cost"`
	Mean   float64   `json:"mean"`
	Stddev float64   `json:"stddev"`
}

// Days whose cost exceeds the trailing mean by > 3 standard deviations (needs >= 7 prior days).
func (q *Queries) Anomalies(ctx context.Context, arg AnomaliesParams) ([]AnomaliesRow, error) {
	rows, err := q.db.Query(ctx, anomalies,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnomaliesRow{}
	for rows.Next() {
		var i AnomaliesRow
		if err := rows.Scan(
			&i.Day,
			&i.Cost,
			&i.Mean,
			&i.Stddev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costByService = `-- name: CostByService :many
SELECT service_name, currency::text AS currency, sum(billed_cost)::float8 AS cost
FROM usage.usage_records
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND recorded_at >= $3 AND recorded_at < $4
GROUP BY service_name, currency ORDER BY cost DESC LIMIT 100
`

type CostByServiceParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type CostByServiceRow struct {
	ServiceName string  `json:"service_name"`
	Currency    string  `json:"currency"`
	Cost        float64 `json:"cost"`
}

// Dominant-currency handling happens in Go; here: cost per service and currency.
func (q *Queries) CostByService(ctx context.Context, arg CostByServiceParams) ([]CostByServiceRow, error) {
	rows, err := q.db.Query(ctx, costByService,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostByServiceRow{}
	for rows.Next() {
		var i CostByServiceRow
		if err := rows.Scan(&i.ServiceName, &i.Currency, &i.Cost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const costDays = `-- name: CostDays :one
SELECT count(DISTINCT date_trunc('day', recorded_at))::int AS days
FROM usage.usage_records
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND recorded_at >= $3 AND recorded_at < $4
`

type CostDaysParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

func (q *Queries) CostDays(ctx context.Context, arg CostDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, costDays,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	var days int32
	err := row.Scan(&days)
	return days, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO finops.budgets (tenant_id, project_id, amount, currency, period)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, project_id, amount, currency::text AS currency, period, created_at
`

type CreateBudgetParams struct {
	TenantID  string  `json:"tenant_id"`
	ProjectID *string `json:"project_id"`
	Amount    float64 `json:"amount"`
	Currency  string  `json:"currency"`
	Period    string  `json:"period"`
}

type CreateBudgetRow struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	Amount    float64   `json:"amount"`
	Currency  string    `json:"currency"`
	Period    string    `json:"period"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (CreateBudgetRow, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.TenantID,
		arg.ProjectID,
		arg.Amount,
		arg.Currency,
		arg.Period,
	)
	var i CreateBudgetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Amount,
		&i.Currency,
		&i.Period,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM finops.budgets WHERE tenant_id = $1 AND id = $2
`

type DeleteBudgetParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudget, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, tenant_id, project_id, amount, currency::text AS currency, period, created_at
FROM finops.budgets WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT 200
`

type ListBudgetsRow struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	Amount    float64   `json:"amount"`
	Currency  string    `json:"currency"`
	Period    string    `json:"period"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListBudgets(ctx context.Context, tenantID string) ([]ListBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listBudgets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsRow{}
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Amount,
			&i.Currency,
			&i.Period,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalCost = `-- name: TotalCost :one
SELECT COALESCE(sum(billed_cost), 0)::float8 AS cost
FROM usage.usage_records
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND ($3::text = '' OR currency = $3::text)
  AND recorded_at >= $4 AND recorded_at < $5
`

type TotalCostParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	Currency  string    `json:"currency"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

func (q *Queries) TotalCost(ctx context.Context, arg TotalCostParams) (float64, error) {
	row := q.db.QueryRow(ctx, totalCost,
		arg.TenantID,
		arg.ProjectID,
		arg.Currency,
		arg.FromTs,
		arg.ToTs,
	)
	var cost float64
	err := row.Scan(&cost)
	return cost, err
}
