// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"encoding/json"
)

const approveJob = `-- name: ApproveJob :exec
UPDATE automation.jobs SET status = 'approved', approved_by = $1, approved_at = now()
WHERE tenant_id = $2 AND id = $3
`

type ApproveJobParams struct {
	Actor    *string `json:"actor"`
	TenantID string  `json:"tenant_id"`
	ID       string  `json:"id"`
}

func (q *Queries) ApproveJob(ctx context.Context, arg ApproveJobParams) error {
	_, err := q.db.Exec(ctx, approveJob, arg.Actor, arg.TenantID, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE automation.jobs SET status = $1, finished_by = $2, finished_at = now(), result_note = $3
WHERE tenant_id = $4 AND id = $5
`

type FinishJobParams struct {
	Status   string  `json:"status"`
	Actor    *string `json:"actor"`
	Note     *string `json:"note"`
	TenantID string  `json:"tenant_id"`
	ID       string  `json:"id"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.Status,
		arg.Actor,
		arg.Note,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, tenant_id, project_id, recommendation_id, kind, status, plan, risk_level, risk_factors, rollback_plan, created_by, created_at, approved_by, approved_at, finished_by, finished_at, result_note FROM automation.jobs WHERE tenant_id = $1 AND id = $2
`

type GetJobParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (AutomationJob, error) {
	row := q.db.QueryRow(ctx, getJob, arg.TenantID, arg.ID)
	var i AutomationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.RecommendationID,
		&i.Kind,
		&i.Status,
		&i.Plan,
		&i.RiskLevel,
		&i.RiskFactors,
		&i.RollbackPlan,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FinishedBy,
		&i.FinishedAt,
		&i.ResultNote,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO automation.jobs (tenant_id, project_id, recommendation_id, kind, plan, risk_level, risk_factors, rollback_plan, created_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, tenant_id, project_id, recommendation_id, kind, status, plan, risk_level, risk_factors, rollback_plan, created_by, created_at, approved_by, approved_at, finished_by, finished_at, result_note
`

type InsertJobParams struct {
	TenantID         string          `json:"tenant_id"`
	ProjectID        string          `json:"project_id"`
	RecommendationID string          `json:"recommendation_id"`
	Kind             string          `json:"kind"`
	Plan             json.RawMessage `json:"plan"`
	RiskLevel        string          `json:"risk_level"`
	RiskFactors      json.RawMessage `json:"risk_factors"`
	RollbackPlan     string          `json:"rollback_plan"`
	CreatedBy        string          `json:"created_by"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (AutomationJob, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.TenantID,
		arg.ProjectID,
		arg.RecommendationID,
		arg.Kind,
		arg.Plan,
		arg.RiskLevel,
		arg.RiskFactors,
		arg.RollbackPlan,
		arg.CreatedBy,
	)
	var i AutomationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.RecommendationID,
		&i.Kind,
		&i.Status,
		&i.Plan,
		&i.RiskLevel,
		&i.RiskFactors,
		&i.RollbackPlan,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FinishedBy,
		&i.FinishedAt,
		&i.ResultNote,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, tenant_id, project_id, recommendation_id, kind, status, plan, risk_level, risk_factors, rollback_plan, created_by, created_at, approved_by, approved_at, finished_by, finished_at, result_note FROM automation.jobs WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListJobsParams struct {
	TenantID string `json:"tenant_id"`
	RowLimit int32  `json:"row_limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]AutomationJob, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationJob{}
	for rows.Next() {
		var i AutomationJob
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.RecommendationID,
			&i.Kind,
			&i.Status,
			&i.Plan,
			&i.RiskLevel,
			&i.RiskFactors,
			&i.RollbackPlan,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.FinishedBy,
			&i.FinishedAt,
			&i.ResultNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJob = `-- name: LockJob :one
SELECT id, tenant_id, project_id, recommendation_id, kind, status, plan, risk_level, risk_factors, rollback_plan, created_by, created_at, approved_by, approved_at, finished_by, finished_at, result_note FROM automation.jobs WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockJobParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

// FOR UPDATE serializes concurrent decisions on the same job.
func (q *Queries) LockJob(ctx context.Context, arg LockJobParams) (AutomationJob, error) {
	row := q.db.QueryRow(ctx, lockJob, arg.TenantID, arg.ID)
	var i AutomationJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.RecommendationID,
		&i.Kind,
		&i.Status,
		&i.Plan,
		&i.RiskLevel,
		&i.RiskFactors,
		&i.RollbackPlan,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FinishedBy,
		&i.FinishedAt,
		&i.ResultNote,
	)
	return i, err
}
