// Package repository is the PostgreSQL adapter of the projects domain (queries generated by sqlc).
package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/audit"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
	"github.com/quixgit/greenops-reliabilix/backend/internal/projects/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/projects/repository/db"
)

type Postgres struct{ Pool *pgxpool.Pool }

func toProject(r db.ProjectsProject) domain.Project {
	return domain.Project{ID: r.ID, TenantID: r.TenantID, Name: r.Name, FunctionalUnit: r.FunctionalUnit, CreatedAt: r.CreatedAt}
}

func (r Postgres) List(ctx context.Context, tenantID string) ([]domain.Project, error) {
	out := []domain.Project{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListProjects(ctx, tenantID)
		for _, p := range rows {
			out = append(out, toProject(p))
		}
		return err
	})
	return out, err
}

func (r Postgres) Get(ctx context.Context, tenantID, id string) (p domain.Project, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		row, err := db.New(tx).GetProject(ctx, db.GetProjectParams{TenantID: tenantID, ID: id})
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		p = toProject(row)
		return err
	})
	return
}

func (r Postgres) Create(ctx context.Context, p domain.Project) (domain.Project, error) {
	err := database.WithTenantTx(ctx, r.Pool, p.TenantID, func(tx pgx.Tx) error {
		row, err := db.New(tx).CreateProject(ctx, db.CreateProjectParams{TenantID: p.TenantID, Name: p.Name, FunctionalUnit: p.FunctionalUnit})
		if err != nil {
			return err
		}
		p = toProject(row)
		return audit.Record(ctx, tx, "project.created", "project:"+p.ID, map[string]any{"name": p.Name})
	})
	if database.IsUniqueViolation(err) {
		return domain.Project{}, domain.ErrDuplicate
	}
	return p, err
}

func (r Postgres) UpsertFunctionalUnits(ctx context.Context, tenantID string, f domain.FunctionalUnits) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		if _, err := db.New(tx).GetProject(ctx, db.GetProjectParams{TenantID: tenantID, ID: f.ProjectID}); err != nil {
			if database.IsNotFound(err) {
				return domain.ErrNotFound
			}
			return err
		}
		if _, err := db.New(tx).UpsertFunctionalUnits(ctx, db.UpsertFunctionalUnitsParams{
			TenantID: tenantID, ProjectID: f.ProjectID, PeriodStart: f.PeriodStart, PeriodEnd: f.PeriodEnd, Units: f.Units}); err != nil {
			return err
		}
		return audit.Record(ctx, tx, "project.functional_units_reported", "project:"+f.ProjectID, map[string]any{"units": f.Units})
	})
}

func (r Postgres) ListFunctionalUnits(ctx context.Context, tenantID, projectID string) ([]domain.FunctionalUnits, error) {
	out := []domain.FunctionalUnits{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListFunctionalUnits(ctx, db.ListFunctionalUnitsParams{TenantID: tenantID, ProjectID: projectID})
		for _, x := range rows {
			out = append(out, domain.FunctionalUnits{ID: x.ID, ProjectID: x.ProjectID, PeriodStart: x.PeriodStart, PeriodEnd: x.PeriodEnd, Units: x.Units})
		}
		return err
	})
	return out, err
}

func (r Postgres) FunctionalUnitsForDay(ctx context.Context, tenantID, projectID string, day time.Time) (u float64, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		u, err = db.New(tx).FunctionalUnitsForDay(ctx, db.FunctionalUnitsForDayParams{TenantID: tenantID, ProjectID: projectID, Day: day})
		return err
	})
	return
}

func (r Postgres) GetPolicy(ctx context.Context, tenantID, projectID string) (p domain.Policy, err error) {
	p = domain.Policy{ProjectID: projectID, AllowedRegions: []string{}}
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		row, err := db.New(tx).GetPolicy(ctx, db.GetPolicyParams{TenantID: tenantID, ProjectID: projectID})
		if database.IsNotFound(err) {
			return nil // no policy yet: residency unknown, no CI thresholds
		}
		if err != nil {
			return err
		}
		p = domain.Policy{ProjectID: projectID, AllowedRegions: row.AllowedRegions, CICarbonWarnKg: row.CiCarbonWarnKg,
			CICarbonBlockKg: row.CiCarbonBlockKg, CICostWarn: row.CiCostWarn, CICostBlock: row.CiCostBlock}
		return nil
	})
	return
}

func (r Postgres) UpsertPolicy(ctx context.Context, tenantID string, p domain.Policy) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		if _, err := q.GetProject(ctx, db.GetProjectParams{TenantID: tenantID, ID: p.ProjectID}); err != nil {
			if database.IsNotFound(err) {
				return domain.ErrNotFound
			}
			return err
		}
		if _, err := q.UpsertPolicy(ctx, db.UpsertPolicyParams{ProjectID: p.ProjectID, TenantID: tenantID, AllowedRegions: p.AllowedRegions,
			CiCarbonWarnKg: p.CICarbonWarnKg, CiCarbonBlockKg: p.CICarbonBlockKg, CiCostWarn: p.CICostWarn, CiCostBlock: p.CICostBlock}); err != nil {
			return err
		}
		return audit.Record(ctx, tx, "project.policy_updated", "project:"+p.ProjectID, map[string]any{"allowed_regions": p.AllowedRegions})
	})
}

// ListForJobs returns every project across tenants (SECURITY DEFINER function; used by schedulers only).
func (r Postgres) ListForJobs(ctx context.Context) ([]domain.JobRef, error) {
	rows, err := r.Pool.Query(ctx, `SELECT tenant_id::text, project_id::text FROM projects.list_projects_for_jobs()`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []domain.JobRef
	for rows.Next() {
		var j domain.JobRef
		if err := rows.Scan(&j.TenantID, &j.ProjectID); err != nil {
			return nil, err
		}
		out = append(out, j)
	}
	return out, rows.Err()
}
