// Package repository implements the dashboard read models on PostgreSQL (queries generated by sqlc).
package repository

import (
	"context"
	"sort"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/dashboard/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/dashboard/repository/db"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/methodology"
)

type Postgres struct{ Pool *pgxpool.Pool }

func (r Postgres) Trend(ctx context.Context, f domain.Filter) ([]domain.TrendPoint, error) {
	out := []domain.TrendPoint{}
	err := database.WithTenantTx(ctx, r.Pool, f.TenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).DashboardTrend(ctx, db.DashboardTrendParams{TenantID: f.TenantID, ProjectID: f.Project,
			MethodologyVersion: methodology.Version, FromTs: f.From, ToTs: f.To})
		for _, x := range rows {
			out = append(out, domain.TrendPoint{Day: x.Day, Cost: x.Cost, CO2eKg: x.CarbonKgCo2e})
		}
		return err
	})
	return out, err
}

func (r Postgres) Providers(ctx context.Context, f domain.Filter) ([]domain.ProviderShare, error) {
	out := []domain.ProviderShare{}
	err := database.WithTenantTx(ctx, r.Pool, f.TenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).DashboardProviders(ctx, db.DashboardProvidersParams{TenantID: f.TenantID, ProjectID: f.Project,
			MethodologyVersion: methodology.Version, FromTs: f.From, ToTs: f.To})
		var total float64
		for _, x := range rows {
			total += x.CarbonKgCo2e
		}
		for _, x := range rows {
			out = append(out, domain.ProviderShare{Provider: x.Provider, CO2eKg: x.CarbonKgCo2e, SharePct: x.CarbonKgCo2e / total * 100})
		}
		return err
	})
	return out, err
}

func (r Postgres) Services(ctx context.Context, f domain.Filter, category string) ([]domain.ServiceRow, error) {
	byName := map[string]*domain.ServiceRow{}
	err := database.WithTenantTx(ctx, r.Pool, f.TenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		costs, err := q.DashboardServiceCost(ctx, db.DashboardServiceCostParams{TenantID: f.TenantID, ProjectID: f.Project, FromTs: f.From, ToTs: f.To, Category: category})
		if err != nil {
			return err
		}
		for _, x := range costs {
			byName[x.ServiceName] = &domain.ServiceRow{Service: x.ServiceName, Category: x.ServiceCategory, Cost: x.Cost, Spark: []float64{}}
		}
		carbonRows, err := q.DashboardServiceCarbon(ctx, db.DashboardServiceCarbonParams{TenantID: f.TenantID, ProjectID: f.Project,
			MethodologyVersion: methodology.Version, FromTs: f.From, ToTs: f.To, Category: category})
		if err != nil {
			return err
		}
		for _, x := range carbonRows {
			s, ok := byName[x.ServiceName]
			if !ok {
				s = &domain.ServiceRow{Service: x.ServiceName, Category: x.ServiceCategory, Spark: []float64{}}
				byName[x.ServiceName] = s
			}
			s.CO2eKg += x.CarbonKgCo2e
			s.Spark = append(s.Spark, x.CarbonKgCo2e)
		}
		return nil
	})
	out := make([]domain.ServiceRow, 0, len(byName))
	for _, s := range byName {
		out = append(out, *s)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Cost > out[j].Cost })
	return out, err
}

// Regions reads global reference data (no tenant): the latest stored reading per region and its 24h change.
func (r Postgres) Regions(ctx context.Context) ([]domain.RegionIntensity, error) {
	rows, err := db.New(r.Pool).DashboardRegions(ctx)
	out := make([]domain.RegionIntensity, 0, len(rows))
	for _, x := range rows {
		ri := domain.RegionIntensity{Region: x.RegionID, GPerKWh: x.GPerKwh, At: x.At}
		if x.PrevGPerKwh != nil && *x.PrevGPerKwh > 0 {
			c := (x.GPerKwh - *x.PrevGPerKwh) / *x.PrevGPerKwh * 100
			ri.ChangePct = &c
		}
		out = append(out, ri)
	}
	return out, err
}

func (r Postgres) Activity(ctx context.Context, tenantID string, limit int) ([]domain.Activity, error) {
	out := []domain.Activity{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).DashboardActivity(ctx, db.DashboardActivityParams{TenantID: tenantID, Actions: domain.UserFacingActions, RowLimit: int32(limit)}) //nolint:gosec // limit clamped to <= 50 by the handler
		for _, x := range rows {
			out = append(out, domain.Activity{ID: x.ID, Action: x.Action, Target: x.Target, At: x.CreatedAt})
		}
		return err
	})
	return out, err
}
