// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects.projects (tenant_id, name, functional_unit)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, functional_unit, created_at
`

type CreateProjectParams struct {
	TenantID       string `json:"tenant_id"`
	Name           string `json:"name"`
	FunctionalUnit string `json:"functional_unit"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (ProjectsProject, error) {
	row := q.db.QueryRow(ctx, createProject, arg.TenantID, arg.Name, arg.FunctionalUnit)
	var i ProjectsProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.FunctionalUnit,
		&i.CreatedAt,
	)
	return i, err
}

const functionalUnitsForDay = `-- name: FunctionalUnitsForDay :one
SELECT COALESCE(sum(units / (period_end - period_start + 1)), 0)::float8 AS units
FROM projects.functional_unit_counts
WHERE tenant_id = $1 AND project_id = $2
  AND period_start <= $3::date AND period_end >= $3::date
`

type FunctionalUnitsForDayParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID string    `json:"project_id"`
	Day       time.Time `json:"day"`
}

// R for a single day: every reported range covering the day contributes units spread evenly over its days.
func (q *Queries) FunctionalUnitsForDay(ctx context.Context, arg FunctionalUnitsForDayParams) (float64, error) {
	row := q.db.QueryRow(ctx, functionalUnitsForDay, arg.TenantID, arg.ProjectID, arg.Day)
	var units float64
	err := row.Scan(&units)
	return units, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT project_id, tenant_id, allowed_regions, ci_carbon_warn_kg, ci_carbon_block_kg, ci_cost_warn, ci_cost_block, updated_at
FROM projects.policies WHERE tenant_id = $1 AND project_id = $2
`

type GetPolicyParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetPolicy(ctx context.Context, arg GetPolicyParams) (ProjectsPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicy, arg.TenantID, arg.ProjectID)
	var i ProjectsPolicy
	err := row.Scan(
		&i.ProjectID,
		&i.TenantID,
		&i.AllowedRegions,
		&i.CiCarbonWarnKg,
		&i.CiCarbonBlockKg,
		&i.CiCostWarn,
		&i.CiCostBlock,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, name, functional_unit, created_at
FROM projects.projects WHERE tenant_id = $1 AND id = $2
`

type GetProjectParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (ProjectsProject, error) {
	row := q.db.QueryRow(ctx, getProject, arg.TenantID, arg.ID)
	var i ProjectsProject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.FunctionalUnit,
		&i.CreatedAt,
	)
	return i, err
}

const listFunctionalUnits = `-- name: ListFunctionalUnits :many
SELECT id, project_id, period_start, period_end, units
FROM projects.functional_unit_counts
WHERE tenant_id = $1 AND project_id = $2
ORDER BY period_start DESC LIMIT 200
`

type ListFunctionalUnitsParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
}

type ListFunctionalUnitsRow struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	Units       float64   `json:"units"`
}

func (q *Queries) ListFunctionalUnits(ctx context.Context, arg ListFunctionalUnitsParams) ([]ListFunctionalUnitsRow, error) {
	rows, err := q.db.Query(ctx, listFunctionalUnits, arg.TenantID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFunctionalUnitsRow{}
	for rows.Next() {
		var i ListFunctionalUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, name, functional_unit, created_at
FROM projects.projects WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT 500
`

func (q *Queries) ListProjects(ctx context.Context, tenantID string) ([]ProjectsProject, error) {
	rows, err := q.db.Query(ctx, listProjects, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsProject{}
	for rows.Next() {
		var i ProjectsProject
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.FunctionalUnit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFunctionalUnits = `-- name: UpsertFunctionalUnits :one
INSERT INTO projects.functional_unit_counts (tenant_id, project_id, period_start, period_end, units)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, period_start, period_end) DO UPDATE SET units = EXCLUDED.units
RETURNING id
`

type UpsertFunctionalUnitsParams struct {
	TenantID    string    `json:"tenant_id"`
	ProjectID   string    `json:"project_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	Units       float64   `json:"units"`
}

func (q *Queries) UpsertFunctionalUnits(ctx context.Context, arg UpsertFunctionalUnitsParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertFunctionalUnits,
		arg.TenantID,
		arg.ProjectID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Units,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertPolicy = `-- name: UpsertPolicy :one
INSERT INTO projects.policies (project_id, tenant_id, allowed_regions, ci_carbon_warn_kg, ci_carbon_block_kg, ci_cost_warn, ci_cost_block)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id) DO UPDATE SET allowed_regions = EXCLUDED.allowed_regions, ci_carbon_warn_kg = EXCLUDED.ci_carbon_warn_kg,
  ci_carbon_block_kg = EXCLUDED.ci_carbon_block_kg, ci_cost_warn = EXCLUDED.ci_cost_warn, ci_cost_block = EXCLUDED.ci_cost_block, updated_at = now()
RETURNING project_id, tenant_id, allowed_regions, ci_carbon_warn_kg, ci_carbon_block_kg, ci_cost_warn, ci_cost_block, updated_at
`

type UpsertPolicyParams struct {
	ProjectID       string   `json:"project_id"`
	TenantID        string   `json:"tenant_id"`
	AllowedRegions  []string `json:"allowed_regions"`
	CiCarbonWarnKg  *float64 `json:"ci_carbon_warn_kg"`
	CiCarbonBlockKg *float64 `json:"ci_carbon_block_kg"`
	CiCostWarn      *float64 `json:"ci_cost_warn"`
	CiCostBlock     *float64 `json:"ci_cost_block"`
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (ProjectsPolicy, error) {
	row := q.db.QueryRow(ctx, upsertPolicy,
		arg.ProjectID,
		arg.TenantID,
		arg.AllowedRegions,
		arg.CiCarbonWarnKg,
		arg.CiCarbonBlockKg,
		arg.CiCostWarn,
		arg.CiCostBlock,
	)
	var i ProjectsPolicy
	err := row.Scan(
		&i.ProjectID,
		&i.TenantID,
		&i.AllowedRegions,
		&i.CiCarbonWarnKg,
		&i.CiCarbonBlockKg,
		&i.CiCostWarn,
		&i.CiCostBlock,
		&i.UpdatedAt,
	)
	return i, err
}
