// Package repository is the PostgreSQL adapter of the carbon domain (queries generated by sqlc).
package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/carbon/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/carbon/repository/db"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
)

type Postgres struct{ Pool *pgxpool.Pool }

func totals(ctx context.Context, q *db.Queries, tenantID string, project *string, from, to time.Time) (domain.Totals, error) {
	row, err := q.CarbonTotals(ctx, db.CarbonTotalsParams{TenantID: tenantID, ProjectID: project, MethodologyVersion: domain.MethodologyVersion, FromTs: from, ToTs: to})
	if err != nil {
		return domain.Totals{}, err
	}
	t := domain.Totals{EnergyKWh: row.EnergyKwh, CO2eKg: row.CarbonKgCo2e, Rows: row.RowCount, Days: int(row.Days)}
	if t.EnergyKWh > 0 {
		t.IntensityGPerKWh = t.CO2eKg * 1000 / t.EnergyKWh
	}
	if row.SciUnits > 0 {
		sci := row.SciGrams / row.SciUnits
		t.SCI = &sci
	}
	return t, nil
}

// Summary returns the window and the preceding window of equal length.
func (r Postgres) Summary(ctx context.Context, tenantID string, project *string, from, to time.Time) (s domain.Summary, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		var err error
		if s.Current, err = totals(ctx, q, tenantID, project, from, to); err != nil {
			return err
		}
		s.Previous, err = totals(ctx, q, tenantID, project, from.Add(-to.Sub(from)), from)
		return err
	})
	return
}

func (r Postgres) Trend(ctx context.Context, tenantID string, project *string, from, to time.Time) ([]domain.TrendPoint, error) {
	out := []domain.TrendPoint{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).CarbonTrend(ctx, db.CarbonTrendParams{TenantID: tenantID, ProjectID: project, MethodologyVersion: domain.MethodologyVersion, FromTs: from, ToTs: to})
		for _, x := range rows {
			out = append(out, domain.TrendPoint{Day: x.Day, CO2eKg: x.CarbonKgCo2e})
		}
		return err
	})
	return out, err
}

const batchSize = 500

// UpsertCalculations stores calculations idempotently. Partitions are ensured first (see usage repository).
func (r Postgres) UpsertCalculations(ctx context.Context, tenantID, projectID string, calcs []domain.Calculation) error {
	if len(calcs) == 0 {
		return nil
	}
	months := map[time.Time]bool{}
	for _, c := range calcs {
		months[time.Date(c.PeriodStart.Year(), c.PeriodStart.Month(), 1, 0, 0, 0, 0, time.UTC)] = true
	}
	for m := range months {
		if _, err := r.Pool.Exec(ctx, `SELECT platform.ensure_month_partition('carbon.calculations', 'period_start', $1::date)`, m); err != nil {
			return err
		}
	}
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		for start := 0; start < len(calcs); start += batchSize {
			end := min(start+batchSize, len(calcs))
			params := make([]db.UpsertCalculationParams, 0, end-start)
			for _, c := range calcs[start:end] {
				params = append(params, db.UpsertCalculationParams{TenantID: tenantID, ProjectID: projectID, Provider: c.Provider, RegionID: c.RegionID,
					ServiceName: c.ServiceName, ServiceCategory: c.ServiceCategory, Method: string(c.Method), PeriodStart: c.PeriodStart, PeriodEnd: c.PeriodEnd,
					EnergyKwh: c.EnergyKWh, IntensityGPerKwh: c.IntensityGPerKWh, EmbodiedG: c.EmbodiedG, CarbonKgCo2e: c.CO2eKg,
					FunctionalUnits: c.FunctionalUnits, SciScore: c.SCIScore, MethodologyVersion: c.MethodologyVersion})
			}
			br := q.UpsertCalculation(ctx, params)
			var first error
			br.Exec(func(_ int, err error) {
				if err != nil && first == nil {
					first = err
				}
			})
			if err := br.Close(); err != nil && first == nil {
				first = err
			}
			if first != nil {
				return first
			}
		}
		return nil
	})
}

// SaveGridIntensity stores a reading in the global reference table (idempotent; no tenant).
func (r Postgres) SaveGridIntensity(ctx context.Context, provider, region string, at time.Time, gPerKWh float64, forecast bool) error {
	return db.New(r.Pool).SaveGridIntensity(ctx, db.SaveGridIntensityParams{Provider: provider, RegionID: region, Ts: at, GCo2ePerKwh: gPerKWh, IsForecast: forecast})
}

// IntensityAt returns the latest stored reading at or before ts, falling back to the latest overall.
func (r Postgres) IntensityAt(ctx context.Context, region string, ts time.Time) (float64, bool, error) {
	q := db.New(r.Pool)
	g, err := q.IntensityAt(ctx, db.IntensityAtParams{RegionID: region, Ts: ts})
	if err == nil {
		return g, true, nil
	}
	if !database.IsNotFound(err) {
		return 0, false, err
	}
	g, err = q.LatestIntensity(ctx, region)
	if database.IsNotFound(err) {
		return 0, false, nil
	}
	return g, err == nil, err
}
