// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertUsageRecord = `-- name: UpsertUsageRecord :batchexec
INSERT INTO usage.usage_records (tenant_id, project_id, connection_id, source, provider, resource_id, resource_type, service_name, service_category,
    region_id, consumed_quantity, consumed_unit, billed_cost, effective_cost, currency, recorded_at, charge_period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17)
ON CONFLICT (tenant_id, project_id, provider, service_name, region_id, resource_id, consumed_unit, recorded_at)
DO UPDATE SET billed_cost = EXCLUDED.billed_cost, effective_cost = EXCLUDED.effective_cost, consumed_quantity = EXCLUDED.consumed_quantity,
              charge_period_end = EXCLUDED.charge_period_end, currency = EXCLUDED.currency, connection_id = EXCLUDED.connection_id
`

type UpsertUsageRecordBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertUsageRecordParams struct {
	TenantID         string    `json:"tenant_id"`
	ProjectID        string    `json:"project_id"`
	ConnectionID     *string   `json:"connection_id"`
	Source           string    `json:"source"`
	Provider         string    `json:"provider"`
	ResourceID       string    `json:"resource_id"`
	ResourceType     string    `json:"resource_type"`
	ServiceName      string    `json:"service_name"`
	ServiceCategory  string    `json:"service_category"`
	RegionID         string    `json:"region_id"`
	ConsumedQuantity *float64  `json:"consumed_quantity"`
	ConsumedUnit     *string   `json:"consumed_unit"`
	BilledCost       float64   `json:"billed_cost"`
	EffectiveCost    float64   `json:"effective_cost"`
	Currency         string    `json:"currency"`
	RecordedAt       time.Time `json:"recorded_at"`
	ChargePeriodEnd  time.Time `json:"charge_period_end"`
}

func (q *Queries) UpsertUsageRecord(ctx context.Context, arg []UpsertUsageRecordParams) *UpsertUsageRecordBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.ProjectID,
			a.ConnectionID,
			a.Source,
			a.Provider,
			a.ResourceID,
			a.ResourceType,
			a.ServiceName,
			a.ServiceCategory,
			a.RegionID,
			a.ConsumedQuantity,
			a.ConsumedUnit,
			a.BilledCost,
			a.EffectiveCost,
			a.Currency,
			a.RecordedAt,
			a.ChargePeriodEnd,
		}
		batch.Queue(upsertUsageRecord, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertUsageRecordBatchResults{br, len(arg), false}
}

func (b *UpsertUsageRecordBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertUsageRecordBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
