// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type AuditAuditLog struct {
	ID          int64           `json:"id"`
	TenantID    string          `json:"tenant_id"`
	ActorUserID string          `json:"actor_user_id"`
	Action      string          `json:"action"`
	Target      string          `json:"target"`
	RequestID   *string         `json:"request_id"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
}

type AutomationJob struct {
	ID               string          `json:"id"`
	TenantID         string          `json:"tenant_id"`
	ProjectID        string          `json:"project_id"`
	RecommendationID string          `json:"recommendation_id"`
	Kind             string          `json:"kind"`
	Status           string          `json:"status"`
	Plan             json.RawMessage `json:"plan"`
	RiskLevel        string          `json:"risk_level"`
	RiskFactors      json.RawMessage `json:"risk_factors"`
	RollbackPlan     string          `json:"rollback_plan"`
	CreatedBy        string          `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	ApprovedBy       *string         `json:"approved_by"`
	ApprovedAt       *time.Time      `json:"approved_at"`
	FinishedBy       *string         `json:"finished_by"`
	FinishedAt       *time.Time      `json:"finished_at"`
	ResultNote       *string         `json:"result_note"`
}

type CarbonCalculation struct {
	ID                 string    `json:"id"`
	TenantID           string    `json:"tenant_id"`
	ProjectID          string    `json:"project_id"`
	Provider           string    `json:"provider"`
	RegionID           string    `json:"region_id"`
	ServiceName        string    `json:"service_name"`
	ServiceCategory    string    `json:"service_category"`
	Method             string    `json:"method"`
	PeriodStart        time.Time `json:"period_start"`
	PeriodEnd          time.Time `json:"period_end"`
	EnergyKwh          float64   `json:"energy_kwh"`
	IntensityGPerKwh   float64   `json:"intensity_g_per_kwh"`
	EmbodiedG          float64   `json:"embodied_g"`
	CarbonKgCo2e       float64   `json:"carbon_kg_co2e"`
	FunctionalUnits    *float64  `json:"functional_units"`
	SciScore           *float64  `json:"sci_score"`
	MethodologyVersion string    `json:"methodology_version"`
	CalculatedAt       time.Time `json:"calculated_at"`
}

type CarbonCalculationsDefault struct {
	ID                 string    `json:"id"`
	TenantID           string    `json:"tenant_id"`
	ProjectID          string    `json:"project_id"`
	Provider           string    `json:"provider"`
	RegionID           string    `json:"region_id"`
	ServiceName        string    `json:"service_name"`
	ServiceCategory    string    `json:"service_category"`
	Method             string    `json:"method"`
	PeriodStart        time.Time `json:"period_start"`
	PeriodEnd          time.Time `json:"period_end"`
	EnergyKwh          float64   `json:"energy_kwh"`
	IntensityGPerKwh   float64   `json:"intensity_g_per_kwh"`
	EmbodiedG          float64   `json:"embodied_g"`
	CarbonKgCo2e       float64   `json:"carbon_kg_co2e"`
	FunctionalUnits    *float64  `json:"functional_units"`
	SciScore           *float64  `json:"sci_score"`
	MethodologyVersion string    `json:"methodology_version"`
	CalculatedAt       time.Time `json:"calculated_at"`
}

type CarbonGridIntensity struct {
	Provider    string    `json:"provider"`
	RegionID    string    `json:"region_id"`
	Ts          time.Time `json:"ts"`
	GCo2ePerKwh float64   `json:"g_co2e_per_kwh"`
	IsForecast  bool      `json:"is_forecast"`
}

type CloudaccountsConnection struct {
	ID            string     `json:"id"`
	TenantID      string     `json:"tenant_id"`
	ProjectID     string     `json:"project_id"`
	Provider      string     `json:"provider"`
	AccountRef    string     `json:"account_ref"`
	CredentialRef string     `json:"credential_ref"`
	ExternalID    string     `json:"external_id"`
	SyncStatus    string     `json:"sync_status"`
	LastError     *string    `json:"last_error"`
	LastSyncAt    *time.Time `json:"last_sync_at"`
	SyncedThrough *time.Time `json:"synced_through"`
	CreatedAt     time.Time  `json:"created_at"`
	ExportBucket  *string    `json:"export_bucket"`
	ExportPrefix  *string    `json:"export_prefix"`
	ExportName    *string    `json:"export_name"`
	ExportRegion  *string    `json:"export_region"`
}

type CloudaccountsSyncRun struct {
	ID           string     `json:"id"`
	TenantID     string     `json:"tenant_id"`
	ConnectionID string     `json:"connection_id"`
	StartedAt    time.Time  `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	Status       string     `json:"status"`
	Records      int32      `json:"records"`
	Error        *string    `json:"error"`
}

type FinopsBudget struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	Amount    float64   `json:"amount"`
	Currency  string    `json:"currency"`
	Period    string    `json:"period"`
	CreatedAt time.Time `json:"created_at"`
}

type FinopsRegionPriceIndex struct {
	Provider  string    `json:"provider"`
	RegionID  string    `json:"region_id"`
	Idx       float64   `json:"idx"`
	Source    string    `json:"source"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProjectsFunctionalUnitCount struct {
	ID          string    `json:"id"`
	TenantID    string    `json:"tenant_id"`
	ProjectID   string    `json:"project_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	Units       float64   `json:"units"`
}

type ProjectsPolicy struct {
	ProjectID       string    `json:"project_id"`
	TenantID        string    `json:"tenant_id"`
	AllowedRegions  []string  `json:"allowed_regions"`
	CiCarbonWarnKg  *float64  `json:"ci_carbon_warn_kg"`
	CiCarbonBlockKg *float64  `json:"ci_carbon_block_kg"`
	CiCostWarn      *float64  `json:"ci_cost_warn"`
	CiCostBlock     *float64  `json:"ci_cost_block"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type ProjectsProject struct {
	ID             string    `json:"id"`
	TenantID       string    `json:"tenant_id"`
	Name           string    `json:"name"`
	FunctionalUnit string    `json:"functional_unit"`
	CreatedAt      time.Time `json:"created_at"`
}

type RecommendationsRecommendation struct {
	ID                          string          `json:"id"`
	TenantID                    string          `json:"tenant_id"`
	ProjectID                   string          `json:"project_id"`
	Type                        string          `json:"type"`
	Title                       string          `json:"title"`
	Provider                    string          `json:"provider"`
	ServiceName                 string          `json:"service_name"`
	CurrentRegion               string          `json:"current_region"`
	RecommendedRegion           string          `json:"recommended_region"`
	EstimatedCarbonReductionPct float64         `json:"estimated_carbon_reduction_pct"`
	CarbonReductionKgMonth      float64         `json:"carbon_reduction_kg_month"`
	EstimatedCostImpact         *float64        `json:"estimated_cost_impact"`
	CostBasis                   string          `json:"cost_basis"`
	Confidence                  float64         `json:"confidence"`
	ComplianceCheck             json.RawMessage `json:"compliance_check"`
	Status                      string          `json:"status"`
	Fingerprint                 string          `json:"fingerprint"`
	DecidedBy                   *string         `json:"decided_by"`
	DecidedAt                   *time.Time      `json:"decided_at"`
	AppliedAt                   *time.Time      `json:"applied_at"`
	CreatedAt                   time.Time       `json:"created_at"`
	Details                     json.RawMessage `json:"details"`
}

type ReportsReport struct {
	ID          string     `json:"id"`
	TenantID    string     `json:"tenant_id"`
	ProjectID   *string    `json:"project_id"`
	Kind        string     `json:"kind"`
	Format      string     `json:"format"`
	PeriodStart time.Time  `json:"period_start"`
	PeriodEnd   time.Time  `json:"period_end"`
	Status      string     `json:"status"`
	ObjectKey   *string    `json:"object_key"`
	Error       *string    `json:"error"`
	RequestedBy string     `json:"requested_by"`
	CreatedAt   time.Time  `json:"created_at"`
	CompletedAt *time.Time `json:"completed_at"`
}

type TenantsApiKey struct {
	ID             string     `json:"id"`
	OrganizationID string     `json:"organization_id"`
	Name           string     `json:"name"`
	Prefix         string     `json:"prefix"`
	KeyHash        string     `json:"key_hash"`
	Role           string     `json:"role"`
	CreatedBy      string     `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	RevokedAt      *time.Time `json:"revoked_at"`
}

type TenantsInvitation struct {
	ID             string     `json:"id"`
	OrganizationID string     `json:"organization_id"`
	Email          string     `json:"email"`
	Role           string     `json:"role"`
	TokenHash      string     `json:"token_hash"`
	CreatedBy      string     `json:"created_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
	AcceptedAt     *time.Time `json:"accepted_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type TenantsMembership struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organization_id"`
	UserID         string    `json:"user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}

type TenantsOrganization struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Plan             string    `json:"plan"`
	WhiteLabelConfig []byte    `json:"white_label_config"`
	CreatedAt        time.Time `json:"created_at"`
}

type TenantsUser struct {
	ID        string    `json:"id"`
	AuthSub   string    `json:"auth_sub"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type UsageUsageRecord struct {
	ID               string    `json:"id"`
	TenantID         string    `json:"tenant_id"`
	ProjectID        string    `json:"project_id"`
	ConnectionID     *string   `json:"connection_id"`
	Source           string    `json:"source"`
	Provider         string    `json:"provider"`
	ResourceID       string    `json:"resource_id"`
	ResourceType     string    `json:"resource_type"`
	ServiceName      string    `json:"service_name"`
	ServiceCategory  string    `json:"service_category"`
	RegionID         string    `json:"region_id"`
	ConsumedQuantity *float64  `json:"consumed_quantity"`
	ConsumedUnit     *string   `json:"consumed_unit"`
	BilledCost       float64   `json:"billed_cost"`
	EffectiveCost    float64   `json:"effective_cost"`
	Currency         string    `json:"currency"`
	RecordedAt       time.Time `json:"recorded_at"`
	ChargePeriodEnd  time.Time `json:"charge_period_end"`
}

type UsageUsageRecordsDefault struct {
	ID               string    `json:"id"`
	TenantID         string    `json:"tenant_id"`
	ProjectID        string    `json:"project_id"`
	ConnectionID     *string   `json:"connection_id"`
	Source           string    `json:"source"`
	Provider         string    `json:"provider"`
	ResourceID       string    `json:"resource_id"`
	ResourceType     string    `json:"resource_type"`
	ServiceName      string    `json:"service_name"`
	ServiceCategory  string    `json:"service_category"`
	RegionID         string    `json:"region_id"`
	ConsumedQuantity *float64  `json:"consumed_quantity"`
	ConsumedUnit     *string   `json:"consumed_unit"`
	BilledCost       float64   `json:"billed_cost"`
	EffectiveCost    float64   `json:"effective_cost"`
	Currency         string    `json:"currency"`
	RecordedAt       time.Time `json:"recorded_at"`
	ChargePeriodEnd  time.Time `json:"charge_period_end"`
}
