// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
	"time"
)

const aggregateDaily = `-- name: AggregateDaily :many
SELECT provider, service_name, service_category, region_id, consumed_unit, currency::text AS currency,
       date_trunc('day', recorded_at)::timestamptz AS day,
       COALESCE(sum(consumed_quantity), 0)::float8 AS quantity,
       sum(billed_cost)::float8 AS billed_cost,
       (count(consumed_quantity) > 0)::bool AS has_quantity
FROM usage.usage_records
WHERE tenant_id = $1 AND project_id = $2
  AND recorded_at >= $3 AND recorded_at < $4
GROUP BY provider, service_name, service_category, region_id, consumed_unit, currency, day
ORDER BY day, service_name
`

type AggregateDailyParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID string    `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type AggregateDailyRow struct {
	Provider        string    `json:"provider"`
	ServiceName     string    `json:"service_name"`
	ServiceCategory string    `json:"service_category"`
	RegionID        string    `json:"region_id"`
	ConsumedUnit    *string   `json:"consumed_unit"`
	Currency        string    `json:"currency"`
	Day             time.Time `json:"day"`
	Quantity        float64   `json:"quantity"`
	BilledCost      float64   `json:"billed_cost"`
	HasQuantity     bool      `json:"has_quantity"`
}

// Daily rollup per workload dimension: the input of the carbon engine.
func (q *Queries) AggregateDaily(ctx context.Context, arg AggregateDailyParams) ([]AggregateDailyRow, error) {
	rows, err := q.db.Query(ctx, aggregateDaily,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateDailyRow{}
	for rows.Next() {
		var i AggregateDailyRow
		if err := rows.Scan(
			&i.Provider,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.RegionID,
			&i.ConsumedUnit,
			&i.Currency,
			&i.Day,
			&i.Quantity,
			&i.BilledCost,
			&i.HasQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsage = `-- name: ListUsage :many
SELECT id, project_id, provider, source, resource_id, resource_type, service_name, service_category, region_id,
       consumed_quantity, consumed_unit, billed_cost, effective_cost, currency, recorded_at, charge_period_end
FROM usage.usage_records
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR project_id = $2)
  AND recorded_at >= $3 AND recorded_at < $4
ORDER BY recorded_at DESC, service_name LIMIT $5
`

type ListUsageParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID *string   `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
	RowLimit  int32     `json:"row_limit"`
}

type ListUsageRow struct {
	ID               string    `json:"id"`
	ProjectID        string    `json:"project_id"`
	Provider         string    `json:"provider"`
	Source           string    `json:"source"`
	ResourceID       string    `json:"resource_id"`
	ResourceType     string    `json:"resource_type"`
	ServiceName      string    `json:"service_name"`
	ServiceCategory  string    `json:"service_category"`
	RegionID         string    `json:"region_id"`
	ConsumedQuantity *float64  `json:"consumed_quantity"`
	ConsumedUnit     *string   `json:"consumed_unit"`
	BilledCost       float64   `json:"billed_cost"`
	EffectiveCost    float64   `json:"effective_cost"`
	Currency         string    `json:"currency"`
	RecordedAt       time.Time `json:"recorded_at"`
	ChargePeriodEnd  time.Time `json:"charge_period_end"`
}

func (q *Queries) ListUsage(ctx context.Context, arg ListUsageParams) ([]ListUsageRow, error) {
	rows, err := q.db.Query(ctx, listUsage,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageRow{}
	for rows.Next() {
		var i ListUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Provider,
			&i.Source,
			&i.ResourceID,
			&i.ResourceType,
			&i.ServiceName,
			&i.ServiceCategory,
			&i.RegionID,
			&i.ConsumedQuantity,
			&i.ConsumedUnit,
			&i.BilledCost,
			&i.EffectiveCost,
			&i.Currency,
			&i.RecordedAt,
			&i.ChargePeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
