// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package db

import (
	"context"
	"time"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO cloudaccounts.connections (tenant_id, project_id, provider, account_ref, credential_ref, external_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, project_id, provider, account_ref, credential_ref, external_id, sync_status, last_error, last_sync_at, synced_through, created_at
`

type CreateConnectionParams struct {
	TenantID      string `json:"tenant_id"`
	ProjectID     string `json:"project_id"`
	Provider      string `json:"provider"`
	AccountRef    string `json:"account_ref"`
	CredentialRef string `json:"credential_ref"`
	ExternalID    string `json:"external_id"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (CloudaccountsConnection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.TenantID,
		arg.ProjectID,
		arg.Provider,
		arg.AccountRef,
		arg.CredentialRef,
		arg.ExternalID,
	)
	var i CloudaccountsConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Provider,
		&i.AccountRef,
		&i.CredentialRef,
		&i.ExternalID,
		&i.SyncStatus,
		&i.LastError,
		&i.LastSyncAt,
		&i.SyncedThrough,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM cloudaccounts.connections WHERE tenant_id = $1 AND id = $2
`

type DeleteConnectionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE cloudaccounts.sync_runs SET finished_at = now(), status = $1, records = $2, error = $3
WHERE tenant_id = $4 AND id = $5
`

type FinishSyncRunParams struct {
	Status   string  `json:"status"`
	Records  int32   `json:"records"`
	Error    *string `json:"error"`
	TenantID string  `json:"tenant_id"`
	ID       string  `json:"id"`
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun,
		arg.Status,
		arg.Records,
		arg.Error,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, tenant_id, project_id, provider, account_ref, credential_ref, external_id, sync_status, last_error, last_sync_at, synced_through, created_at
FROM cloudaccounts.connections WHERE tenant_id = $1 AND id = $2
`

type GetConnectionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (CloudaccountsConnection, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.TenantID, arg.ID)
	var i CloudaccountsConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Provider,
		&i.AccountRef,
		&i.CredentialRef,
		&i.ExternalID,
		&i.SyncStatus,
		&i.LastError,
		&i.LastSyncAt,
		&i.SyncedThrough,
		&i.CreatedAt,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT id, tenant_id, project_id, provider, account_ref, credential_ref, external_id, sync_status, last_error, last_sync_at, synced_through, created_at
FROM cloudaccounts.connections WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT 500
`

func (q *Queries) ListConnections(ctx context.Context, tenantID string) ([]CloudaccountsConnection, error) {
	rows, err := q.db.Query(ctx, listConnections, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CloudaccountsConnection{}
	for rows.Next() {
		var i CloudaccountsConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Provider,
			&i.AccountRef,
			&i.CredentialRef,
			&i.ExternalID,
			&i.SyncStatus,
			&i.LastError,
			&i.LastSyncAt,
			&i.SyncedThrough,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRuns = `-- name: ListSyncRuns :many
SELECT id, connection_id, started_at, finished_at, status, records, error
FROM cloudaccounts.sync_runs WHERE tenant_id = $1 AND connection_id = $2
ORDER BY started_at DESC LIMIT 20
`

type ListSyncRunsParams struct {
	TenantID     string `json:"tenant_id"`
	ConnectionID string `json:"connection_id"`
}

type ListSyncRunsRow struct {
	ID           string     `json:"id"`
	ConnectionID string     `json:"connection_id"`
	StartedAt    time.Time  `json:"started_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	Status       string     `json:"status"`
	Records      int32      `json:"records"`
	Error        *string    `json:"error"`
}

func (q *Queries) ListSyncRuns(ctx context.Context, arg ListSyncRunsParams) ([]ListSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listSyncRuns, arg.TenantID, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncRunsRow{}
	for rows.Next() {
		var i ListSyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Records,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConnectionSynced = `-- name: MarkConnectionSynced :exec
UPDATE cloudaccounts.connections
SET sync_status = 'healthy', last_error = NULL, last_sync_at = now(), synced_through = $1
WHERE tenant_id = $2 AND id = $3
`

type MarkConnectionSyncedParams struct {
	SyncedThrough *time.Time `json:"synced_through"`
	TenantID      string     `json:"tenant_id"`
	ID            string     `json:"id"`
}

func (q *Queries) MarkConnectionSynced(ctx context.Context, arg MarkConnectionSyncedParams) error {
	_, err := q.db.Exec(ctx, markConnectionSynced, arg.SyncedThrough, arg.TenantID, arg.ID)
	return err
}

const setConnectionStatus = `-- name: SetConnectionStatus :exec
UPDATE cloudaccounts.connections SET sync_status = $1, last_error = $2
WHERE tenant_id = $3 AND id = $4
`

type SetConnectionStatusParams struct {
	Status    string  `json:"status"`
	LastError *string `json:"last_error"`
	TenantID  string  `json:"tenant_id"`
	ID        string  `json:"id"`
}

func (q *Queries) SetConnectionStatus(ctx context.Context, arg SetConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, setConnectionStatus,
		arg.Status,
		arg.LastError,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const startSyncRun = `-- name: StartSyncRun :one
INSERT INTO cloudaccounts.sync_runs (tenant_id, connection_id) VALUES ($1, $2) RETURNING id
`

type StartSyncRunParams struct {
	TenantID     string `json:"tenant_id"`
	ConnectionID string `json:"connection_id"`
}

func (q *Queries) StartSyncRun(ctx context.Context, arg StartSyncRunParams) (string, error) {
	row := q.db.QueryRow(ctx, startSyncRun, arg.TenantID, arg.ConnectionID)
	var id string
	err := row.Scan(&id)
	return id, err
}
