// Package repository is the PostgreSQL adapter of the usage domain (queries generated by sqlc).
package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/focus"
	"github.com/quixgit/greenops-reliabilix/backend/internal/usage/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/usage/repository/db"
)

type Postgres struct{ Pool *pgxpool.Pool }

const batchSize = 500

// ensurePartitions creates the monthly partitions the records fall into. It must happen before the
// insert: a partition cannot be created later if the DEFAULT partition already holds rows for its range.
func (r Postgres) ensurePartitions(ctx context.Context, recs []focus.Record) error {
	months := map[time.Time]bool{}
	for _, x := range recs {
		months[time.Date(x.ChargePeriodStart.Year(), x.ChargePeriodStart.Month(), 1, 0, 0, 0, 0, time.UTC)] = true
	}
	for m := range months {
		if _, err := r.Pool.Exec(ctx, `SELECT platform.ensure_month_partition('usage.usage_records', 'recorded_at', $1::date)`, m); err != nil {
			return err
		}
	}
	return nil
}

func (r Postgres) Upsert(ctx context.Context, tenantID, projectID, connectionID string, recs []focus.Record) error {
	if len(recs) == 0 {
		return nil
	}
	if err := r.ensurePartitions(ctx, recs); err != nil {
		return err
	}
	var conn *string
	if connectionID != "" {
		conn = &connectionID
	}
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		for start := 0; start < len(recs); start += batchSize {
			end := min(start+batchSize, len(recs))
			params := make([]db.UpsertUsageRecordParams, 0, end-start)
			for _, x := range recs[start:end] {
				params = append(params, db.UpsertUsageRecordParams{
					TenantID: tenantID, ProjectID: projectID, ConnectionID: conn, Source: x.Source, Provider: x.Provider,
					ResourceID: x.ResourceID, ResourceType: x.ResourceType, ServiceName: x.ServiceName, ServiceCategory: x.ServiceCategory,
					RegionID: x.RegionID, ConsumedQuantity: x.ConsumedQuantity, ConsumedUnit: x.ConsumedUnit, BilledCost: x.BilledCost,
					EffectiveCost: x.EffectiveCost, Currency: x.Currency, RecordedAt: x.ChargePeriodStart, ChargePeriodEnd: x.ChargePeriodEnd,
				})
			}
			br := q.UpsertUsageRecord(ctx, params)
			var first error
			br.Exec(func(_ int, err error) {
				if err != nil && first == nil {
					first = err
				}
			})
			if err := br.Close(); err != nil && first == nil {
				first = err
			}
			if first != nil {
				return first
			}
		}
		return nil
	})
}

func (r Postgres) List(ctx context.Context, tenantID string, projectID *string, from, to time.Time, limit int) ([]domain.Record, error) {
	out := []domain.Record{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListUsage(ctx, db.ListUsageParams{TenantID: tenantID, ProjectID: projectID, FromTs: from, ToTs: to, RowLimit: int32(limit)}) //nolint:gosec // limit is clamped to <= 1000 by the handler
		for _, x := range rows {
			out = append(out, domain.Record{ID: x.ID, ProjectID: x.ProjectID, Provider: x.Provider, Source: x.Source, ResourceID: x.ResourceID,
				ResourceType: x.ResourceType, ServiceName: x.ServiceName, ServiceCategory: x.ServiceCategory, RegionID: x.RegionID,
				ConsumedQuantity: x.ConsumedQuantity, ConsumedUnit: x.ConsumedUnit, BilledCost: x.BilledCost, EffectiveCost: x.EffectiveCost,
				Currency: x.Currency, ChargePeriodStart: x.RecordedAt, ChargePeriodEnd: x.ChargePeriodEnd})
		}
		return err
	})
	return out, err
}

func (r Postgres) DailyAggregates(ctx context.Context, tenantID, projectID string, from, to time.Time) ([]domain.DailyAggregate, error) {
	out := []domain.DailyAggregate{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).AggregateDaily(ctx, db.AggregateDailyParams{TenantID: tenantID, ProjectID: projectID, FromTs: from, ToTs: to})
		for _, x := range rows {
			out = append(out, domain.DailyAggregate{Provider: x.Provider, ServiceName: x.ServiceName, ServiceCategory: x.ServiceCategory,
				RegionID: x.RegionID, Currency: x.Currency, ConsumedUnit: x.ConsumedUnit, Day: x.Day, Quantity: x.Quantity,
				HasQuantity: x.HasQuantity, BilledCost: x.BilledCost})
		}
		return err
	})
	return out, err
}
