// Package repository is the PostgreSQL adapter of the finops domain (queries generated by sqlc).
package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/finops/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/finops/repository/db"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/audit"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
)

type Postgres struct{ Pool *pgxpool.Pool }

// Summary aggregates cost by service for the window and totals the preceding window of equal length.
// Phase 1 assumes a single billing currency: when several exist only the dominant one is reported
// (FX normalization is phase 2).
func (r Postgres) Summary(ctx context.Context, tenantID string, project *string, from, to time.Time) (domain.Summary, error) {
	s := domain.Summary{ByService: []domain.Line{}}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		rows, err := q.CostByService(ctx, db.CostByServiceParams{TenantID: tenantID, ProjectID: project, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		for _, x := range rows {
			if s.Currency == "" {
				s.Currency = x.Currency
			}
			if x.Currency == s.Currency {
				s.TotalCost += x.Cost
				s.ByService = append(s.ByService, domain.Line{Service: x.ServiceName, Cost: x.Cost})
				s.HasData = true
			}
		}
		prevFrom := from.Add(-to.Sub(from))
		if s.PreviousTotalCost, err = q.TotalCost(ctx, db.TotalCostParams{TenantID: tenantID, ProjectID: project, Currency: s.Currency, FromTs: prevFrom, ToTs: from}); err != nil {
			return err
		}
		curDays, err := q.CostDays(ctx, db.CostDaysParams{TenantID: tenantID, ProjectID: project, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		prevDays, err := q.CostDays(ctx, db.CostDaysParams{TenantID: tenantID, ProjectID: project, FromTs: prevFrom, ToTs: from})
		if err != nil {
			return err
		}
		windowDays := int(to.Sub(from).Hours()/24 + 0.5)
		need := int(float64(windowDays)*0.8 + 0.5)
		s.PreviousComparable = windowDays > 0 && int(curDays) >= need && int(prevDays) >= need
		return nil
	})
	return s, err
}

func toBudget(id string, project *string, amount float64, currency, period string, created time.Time) domain.Budget {
	return domain.Budget{ID: id, ProjectID: project, Amount: amount, Currency: currency, Period: period, CreatedAt: created}
}

func (r Postgres) ListBudgets(ctx context.Context, tenantID string) ([]domain.Budget, error) {
	out := []domain.Budget{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListBudgets(ctx, tenantID)
		for _, x := range rows {
			out = append(out, toBudget(x.ID, x.ProjectID, x.Amount, x.Currency, x.Period, x.CreatedAt))
		}
		return err
	})
	return out, err
}

func (r Postgres) CreateBudget(ctx context.Context, tenantID string, b domain.Budget) (domain.Budget, error) {
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		x, err := db.New(tx).CreateBudget(ctx, db.CreateBudgetParams{TenantID: tenantID, ProjectID: b.ProjectID, Amount: b.Amount, Currency: b.Currency, Period: b.Period})
		if err != nil {
			return err
		}
		b = toBudget(x.ID, x.ProjectID, x.Amount, x.Currency, x.Period, x.CreatedAt)
		return audit.Record(ctx, tx, "budget.created", "budget:"+b.ID, map[string]any{"amount": b.Amount, "period": b.Period})
	})
	return b, err
}

func (r Postgres) DeleteBudget(ctx context.Context, tenantID, id string) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		n, err := db.New(tx).DeleteBudget(ctx, db.DeleteBudgetParams{TenantID: tenantID, ID: id})
		if err != nil {
			return err
		}
		if n == 0 {
			return domain.ErrNotFound
		}
		return audit.Record(ctx, tx, "budget.deleted", "budget:"+id, nil)
	})
}

func (r Postgres) Spent(ctx context.Context, tenantID string, project *string, currency string, from, to time.Time) (v float64, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		v, err = db.New(tx).TotalCost(ctx, db.TotalCostParams{TenantID: tenantID, ProjectID: project, Currency: currency, FromTs: from, ToTs: to})
		return err
	})
	return
}

func (r Postgres) Anomalies(ctx context.Context, tenantID string, project *string, from, to time.Time) ([]domain.Anomaly, error) {
	out := []domain.Anomaly{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).Anomalies(ctx, db.AnomaliesParams{TenantID: tenantID, ProjectID: project, FromTs: from, ToTs: to})
		for _, x := range rows {
			out = append(out, domain.Anomaly{Day: x.Day, Cost: x.Cost, Mean: x.Mean, Stddev: x.Stddev})
		}
		return err
	})
	return out, err
}
