// Package repository is the PostgreSQL adapter of the reports domain (queries generated by sqlc).
package repository

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/audit"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/methodology"
	"github.com/quixgit/greenops-reliabilix/backend/internal/reports/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/reports/repository/db"
)

type Postgres struct{ Pool *pgxpool.Pool }

func toDomain(x db.ReportsReport) domain.Report {
	return domain.Report{ID: x.ID, ProjectID: x.ProjectID, Kind: domain.Kind(x.Kind), Format: domain.Format(x.Format), PeriodStart: x.PeriodStart,
		PeriodEnd: x.PeriodEnd, Status: domain.Status(x.Status), ObjectKey: x.ObjectKey, Error: x.Error, RequestedBy: x.RequestedBy,
		CreatedAt: x.CreatedAt, CompletedAt: x.CompletedAt}
}

func (r Postgres) Insert(ctx context.Context, tenantID string, rep domain.Report) (out domain.Report, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		x, err := db.New(tx).InsertReport(ctx, db.InsertReportParams{TenantID: tenantID, ProjectID: rep.ProjectID, Kind: string(rep.Kind), Format: string(rep.Format),
			PeriodStart: rep.PeriodStart, PeriodEnd: rep.PeriodEnd, RequestedBy: rep.RequestedBy})
		if err != nil {
			return err
		}
		out = toDomain(db.ReportsReport(x))
		return audit.Record(ctx, tx, "report.requested", "report:"+out.ID, map[string]any{"kind": rep.Kind, "format": rep.Format})
	})
	return
}

func (r Postgres) List(ctx context.Context, tenantID string) ([]domain.Report, error) {
	out := []domain.Report{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListReports(ctx, tenantID)
		for _, x := range rows {
			out = append(out, toDomain(db.ReportsReport(x)))
		}
		return err
	})
	return out, err
}

func (r Postgres) Get(ctx context.Context, tenantID, id string) (rep domain.Report, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		x, err := db.New(tx).GetReport(ctx, db.GetReportParams{TenantID: tenantID, ID: id})
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		rep = toDomain(db.ReportsReport(x))
		return err
	})
	return
}

func (r Postgres) SetReady(ctx context.Context, tenantID, id, objectKey string) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		if err := db.New(tx).SetReportReady(ctx, db.SetReportReadyParams{TenantID: tenantID, ID: id, ObjectKey: &objectKey}); err != nil {
			return err
		}
		return audit.Record(audit.WithTenant(ctx, tenantID), tx, "report.generated", "report:"+id, nil)
	})
}

func (r Postgres) SetFailed(ctx context.Context, tenantID, id, message string) error {
	return database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		return db.New(tx).SetReportFailed(ctx, db.SetReportFailedParams{TenantID: tenantID, ID: id, Error: &message})
	})
}

func f(v float64) string     { return strconv.FormatFloat(v, 'f', -1, 64) }
func day(t time.Time) string { return t.UTC().Format(time.DateOnly) }

func period(from, to time.Time) string {
	return fmt.Sprintf("%s to %s", day(from), day(to.AddDate(0, 0, -1)))
}

func methodologyNotes() []string {
	n := []string{fmt.Sprintf("Methodology %s (%s). cost_based rows are spend-derived estimates with low confidence; usage_based rows use measured consumption.", methodology.Current.Version, methodology.Current.Status)}
	if methodology.Current.Status == "provisional" {
		n = append(n, "Coefficients are provisional: do not use these figures for external sustainability reporting yet.")
	}
	return n
}

func (r Postgres) CarbonTable(ctx context.Context, tenantID string, project *string, from, to time.Time) (t domain.Table, err error) {
	t = domain.Table{Title: "Carbon footprint report", Period: period(from, to), Notes: methodologyNotes(),
		Headers: []string{"day", "provider", "service", "region", "method", "energy_kwh", "carbon_kg_co2e", "methodology_version"}}
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ReportCarbonDaily(ctx, db.ReportCarbonDailyParams{TenantID: tenantID, ProjectID: project, FromTs: from, ToTs: to})
		for _, x := range rows {
			t.Rows = append(t.Rows, []string{day(x.Day), x.Provider, x.ServiceName, x.RegionID, x.Method, f(x.EnergyKwh), f(x.CarbonKgCo2e), x.MethodologyVersion})
		}
		return err
	})
	return
}

func (r Postgres) FinopsTable(ctx context.Context, tenantID string, project *string, from, to time.Time) (t domain.Table, err error) {
	t = domain.Table{Title: "Cloud cost report", Period: period(from, to),
		Notes:   []string{"Costs follow FOCUS: billed_cost = BilledCost, effective_cost = EffectiveCost, in the billing currency (no FX conversion)."},
		Headers: []string{"day", "provider", "service", "category", "region", "billed_cost", "effective_cost", "currency"}}
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ReportCostDaily(ctx, db.ReportCostDailyParams{TenantID: tenantID, ProjectID: project, FromTs: from, ToTs: to})
		for _, x := range rows {
			t.Rows = append(t.Rows, []string{day(x.Day), x.Provider, x.ServiceName, x.ServiceCategory, x.RegionID, f(x.BilledCost), f(x.EffectiveCost), x.Currency})
		}
		return err
	})
	return
}

// SCITable reports the daily SCI per project. Days without reported functional units show an empty SCI.
func (r Postgres) SCITable(ctx context.Context, tenantID string, project *string, from, to time.Time) (t domain.Table, err error) {
	t = domain.Table{Title: "Software Carbon Intensity (SCI) report", Period: period(from, to),
		Notes:   append(methodologyNotes(), "SCI = ((E x I) + M) / R in gCO2e per functional unit; M (embodied) is 0 in this methodology version (operational emissions only). Days without reported functional units have no SCI."),
		Headers: []string{"project", "functional_unit", "day", "carbon_kg_co2e", "functional_units", "sci_g_per_unit", "methodology_version"}}
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ReportSCIDaily(ctx, db.ReportSCIDailyParams{TenantID: tenantID, ProjectID: project, FromTs: from, ToTs: to})
		for _, x := range rows {
			sci := ""
			if x.FunctionalUnits > 0 {
				sci = f(x.CarbonKgCo2e * 1000 / x.FunctionalUnits)
			}
			units := ""
			if x.FunctionalUnits > 0 {
				units = f(x.FunctionalUnits)
			}
			t.Rows = append(t.Rows, []string{x.Project, x.FunctionalUnit, day(x.Day), f(x.CarbonKgCo2e), units, sci, x.MethodologyVersion})
		}
		return err
	})
	return
}

// SustainabilityTable is the executive summary of the window. It states how much of the footprint rests on
// measured usage and how much on spend-based estimates, so a reader can judge the figures.
func (r Postgres) SustainabilityTable(ctx context.Context, tenantID string, project *string, from, to time.Time) (t domain.Table, err error) {
	t = domain.Table{Title: "Sustainability summary", Period: period(from, to),
		Notes:   append(methodologyNotes(), "Emissions are operational only (embodied emissions are 0 in this methodology version). Recommendation figures are modelled monthly effects, not measured savings."),
		Headers: []string{"section", "item", "value", "unit"}}
	add := func(section, item, value, unit string) { t.Rows = append(t.Rows, []string{section, item, value, unit}) }
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		methods, err := q.ReportSustainabilityByMethod(ctx, db.ReportSustainabilityByMethodParams{TenantID: tenantID, ProjectID: project,
			MethodologyVersion: methodology.Version, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		var energy, carbon, usageBased float64
		for _, m := range methods {
			energy += m.EnergyKwh
			carbon += m.CarbonKg
			if m.Method == "usage_based" {
				usageBased = m.CarbonKg
			}
		}
		add("Totals", "Energy", f(energy), "kWh")
		add("Totals", "Carbon", f(carbon), "kgCO2e")
		if energy > 0 {
			add("Totals", "Average grid intensity", f(carbon*1000/energy), "gCO2e/kWh")
		}
		if carbon > 0 {
			add("Data quality", "Carbon from measured usage", f(usageBased/carbon*100), "%")
			add("Data quality", "Carbon estimated from spend", f((carbon-usageBased)/carbon*100), "%")
		}
		services, err := q.ReportSustainabilityTopServices(ctx, db.ReportSustainabilityTopServicesParams{TenantID: tenantID, ProjectID: project,
			MethodologyVersion: methodology.Version, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		for _, s := range services {
			add("Top services by carbon", s.Provider+" / "+s.ServiceName, f(s.CarbonKg), "kgCO2e")
		}
		regions, err := q.ReportSustainabilityTopRegions(ctx, db.ReportSustainabilityTopRegionsParams{TenantID: tenantID, ProjectID: project,
			MethodologyVersion: methodology.Version, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		for _, g := range regions {
			add("Top regions by carbon", g.RegionID, f(g.CarbonKg), "kgCO2e")
		}
		recs, err := q.ReportSustainabilityRecommendations(ctx, db.ReportSustainabilityRecommendationsParams{TenantID: tenantID, ProjectID: project, ToTs: to})
		if err != nil {
			return err
		}
		for _, x := range recs {
			add("Recommendations ("+x.Status+")", "Count", strconv.Itoa(int(x.N)), "recommendations")
			add("Recommendations ("+x.Status+")", "Modelled effect", f(x.KgMonth), "kgCO2e/month")
		}
		return nil
	})
	return
}
