// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const acceptInvitation = `-- name: AcceptInvitation :one
SELECT tenants.accept_invitation($1::text, $2::text, $3::text)::uuid AS tenant_id
`

type AcceptInvitationParams struct {
	TokenHash string `json:"token_hash"`
	Sub       string `json:"sub"`
	Email     string `json:"email"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (string, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.TokenHash, arg.Sub, arg.Email)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM tenants.memberships WHERE organization_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO tenants.api_keys (organization_id, name, prefix, key_hash, role, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, prefix, role, created_at
`

type CreateAPIKeyParams struct {
	TenantID  string `json:"tenant_id"`
	Name      string `json:"name"`
	Prefix    string `json:"prefix"`
	KeyHash   string `json:"key_hash"`
	Role      string `json:"role"`
	CreatedBy string `json:"created_by"`
}

type CreateAPIKeyRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Prefix    string    `json:"prefix"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Role,
		arg.CreatedBy,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO tenants.invitations (organization_id, email, role, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, role, expires_at, created_at
`

type CreateInvitationParams struct {
	TenantID  string    `json:"tenant_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	TokenHash string    `json:"token_hash"`
	CreatedBy string    `json:"created_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreateInvitationRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM tenants.memberships WHERE organization_id = $1 AND id = $2
`

type DeleteMemberParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.TenantID, arg.ID)
	return err
}

const getMember = `-- name: GetMember :one
SELECT m.id, m.user_id, u.auth_sub, u.email, m.role, m.created_at
FROM tenants.memberships m JOIN tenants.users u ON u.id = m.user_id
WHERE m.organization_id = $1 AND m.id = $2 FOR UPDATE OF m
`

type GetMemberParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

type GetMemberRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	AuthSub   string    `json:"auth_sub"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error) {
	row := q.db.QueryRow(ctx, getMember, arg.TenantID, arg.ID)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthSub,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, plan, created_at FROM tenants.organizations WHERE id = $1
`

type GetOrganizationRow struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetOrganization(ctx context.Context, tenantID string) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization, tenantID)
	var i GetOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, prefix, role, created_by, created_at, last_used_at, revoked_at
FROM tenants.api_keys WHERE organization_id = $1 ORDER BY created_at DESC LIMIT 100
`

type ListAPIKeysRow struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	Role       string     `json:"role"`
	CreatedBy  string     `json:"created_by"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, tenantID string) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, action, target, COALESCE(request_id, '')::text AS request_id, metadata, created_at
FROM audit.audit_logs WHERE tenant_id = $1 AND ($2::text = '' OR action = $2::text)
ORDER BY created_at DESC, id DESC LIMIT $3
`

type ListAuditLogParams struct {
	TenantID string `json:"tenant_id"`
	Action   string `json:"action"`
	RowLimit int32  `json:"row_limit"`
}

type ListAuditLogRow struct {
	ID          int64           `json:"id"`
	ActorUserID string          `json:"actor_user_id"`
	Action      string          `json:"action"`
	Target      string          `json:"target"`
	RequestID   string          `json:"request_id"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.TenantID, arg.Action, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.Target,
			&i.RequestID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, email, role, created_by, expires_at, accepted_at, created_at
FROM tenants.invitations WHERE organization_id = $1 ORDER BY created_at DESC LIMIT 100
`

type ListInvitationsRow struct {
	ID         string     `json:"id"`
	Email      string     `json:"email"`
	Role       string     `json:"role"`
	CreatedBy  string     `json:"created_by"`
	ExpiresAt  time.Time  `json:"expires_at"`
	AcceptedAt *time.Time `json:"accepted_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

func (q *Queries) ListInvitations(ctx context.Context, tenantID string) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.user_id, u.auth_sub, u.email, m.role, m.created_at
FROM tenants.memberships m JOIN tenants.users u ON u.id = m.user_id
WHERE m.organization_id = $1 ORDER BY m.created_at
`

type ListMembersRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	AuthSub   string    `json:"auth_sub"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListMembers(ctx context.Context, tenantID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthSub,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onboard = `-- name: Onboard :one
SELECT tenants.onboard($1::text, $2::text, $3::text)::uuid AS tenant_id
`

type OnboardParams struct {
	Sub     string `json:"sub"`
	Email   string `json:"email"`
	OrgName string `json:"org_name"`
}

func (q *Queries) Onboard(ctx context.Context, arg OnboardParams) (string, error) {
	row := q.db.QueryRow(ctx, onboard, arg.Sub, arg.Email, arg.OrgName)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE tenants.api_keys SET revoked_at = now() WHERE organization_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE tenants.memberships SET role = $1 WHERE organization_id = $2 AND id = $3
`

type UpdateMemberRoleParams struct {
	Role     string `json:"role"`
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.Role, arg.TenantID, arg.ID)
	return err
}
