// Package repository is the PostgreSQL adapter of the automation domain (queries generated by sqlc).
package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/automation/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/automation/repository/db"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/audit"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
)

type Postgres struct{ Pool *pgxpool.Pool }

func toDomain(x db.AutomationJob) (domain.Job, error) {
	j := domain.Job{ID: x.ID, ProjectID: x.ProjectID, RecommendationID: x.RecommendationID, Kind: domain.Kind(x.Kind), Status: domain.Status(x.Status),
		Risk: domain.Risk{Level: domain.RiskLevel(x.RiskLevel)}, RollbackPlan: x.RollbackPlan, CreatedBy: x.CreatedBy, CreatedAt: x.CreatedAt,
		ApprovedBy: x.ApprovedBy, ApprovedAt: x.ApprovedAt, FinishedBy: x.FinishedBy, FinishedAt: x.FinishedAt, ResultNote: x.ResultNote}
	if err := json.Unmarshal(x.Plan, &j.Plan); err != nil {
		return domain.Job{}, err
	}
	if err := json.Unmarshal(x.RiskFactors, &j.Risk.Factors); err != nil {
		return domain.Job{}, err
	}
	return j, nil
}

func (r Postgres) Insert(ctx context.Context, tenantID string, j domain.Job) (out domain.Job, err error) {
	plan, err := json.Marshal(j.Plan)
	if err != nil {
		return out, err
	}
	factors, err := json.Marshal(j.Risk.Factors)
	if err != nil {
		return out, err
	}
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		row, err := db.New(tx).InsertJob(ctx, db.InsertJobParams{TenantID: tenantID, ProjectID: j.ProjectID, RecommendationID: j.RecommendationID,
			Kind: string(j.Kind), Plan: plan, RiskLevel: string(j.Risk.Level), RiskFactors: factors, RollbackPlan: j.RollbackPlan, CreatedBy: j.CreatedBy})
		if err != nil {
			return err
		}
		if out, err = toDomain(row); err != nil {
			return err
		}
		return audit.Record(ctx, tx, "automation.job_planned", "job:"+out.ID,
			map[string]any{"recommendation": j.RecommendationID, "kind": j.Kind, "risk": j.Risk.Level})
	})
	if database.IsUniqueViolation(err) {
		return domain.Job{}, domain.ErrActiveJobExists
	}
	return out, err
}

func (r Postgres) List(ctx context.Context, tenantID string, limit int) ([]domain.Job, error) {
	out := []domain.Job{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListJobs(ctx, db.ListJobsParams{TenantID: tenantID, RowLimit: int32(limit)}) //nolint:gosec // limit clamped by the handler
		if err != nil {
			return err
		}
		for _, x := range rows {
			j, err := toDomain(x)
			if err != nil {
				return err
			}
			out = append(out, j)
		}
		return nil
	})
	return out, err
}

func (r Postgres) Get(ctx context.Context, tenantID, id string) (j domain.Job, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		x, err := db.New(tx).GetJob(ctx, db.GetJobParams{TenantID: tenantID, ID: id})
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		if err != nil {
			return err
		}
		j, err = toDomain(x)
		return err
	})
	return
}

// Transition locks the job, validates the status change, runs check against the current state, writes it and the audit entry in one
// transaction. The actor is recorded as approver or finisher; the note is stored for finishing outcomes.
func (r Postgres) Transition(ctx context.Context, tenantID, id string, to domain.Status, actor, note string, check func(*domain.Job) error) (j domain.Job, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		x, err := q.LockJob(ctx, db.LockJobParams{TenantID: tenantID, ID: id})
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		if err != nil {
			return err
		}
		if j, err = toDomain(x); err != nil {
			return err
		}
		next := j // validate the move on a copy: check sees the state the decision is made from
		if err := next.Transition(to); err != nil {
			return err
		}
		if check != nil {
			if err := check(&j); err != nil {
				return err
			}
		}
		if to == domain.Approved {
			err = q.ApproveJob(ctx, db.ApproveJobParams{TenantID: tenantID, ID: id, Actor: &actor})
		} else {
			var n *string
			if note != "" {
				n = &note
			}
			err = q.FinishJob(ctx, db.FinishJobParams{TenantID: tenantID, ID: id, Status: string(to), Actor: &actor, Note: n})
		}
		if err != nil {
			return err
		}
		return audit.Record(ctx, tx, "automation.job_"+string(to), "job:"+id, map[string]any{"kind": j.Kind, "recommendation": j.RecommendationID})
	})
	if err == nil { // return the persisted state (approver, timestamps, note)
		j, err = r.Get(ctx, tenantID, id)
	}
	return
}
