// Package repository is the PostgreSQL adapter of the recommendations domain (queries generated by sqlc).
package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/audit"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/database"
	"github.com/quixgit/greenops-reliabilix/backend/internal/platform/methodology"
	"github.com/quixgit/greenops-reliabilix/backend/internal/recommendations/domain"
	"github.com/quixgit/greenops-reliabilix/backend/internal/recommendations/repository/db"
)

type Postgres struct{ Pool *pgxpool.Pool }

func toDomain(x db.RecommendationsRecommendation) (domain.Recommendation, error) {
	var cc domain.ComplianceCheck
	if err := json.Unmarshal(x.ComplianceCheck, &cc); err != nil {
		return domain.Recommendation{}, err
	}
	return domain.Recommendation{ID: x.ID, ProjectID: x.ProjectID, Type: domain.Type(x.Type), Title: x.Title, Provider: x.Provider,
		ServiceName: x.ServiceName, CurrentRegion: x.CurrentRegion, RecommendedRegion: x.RecommendedRegion,
		CarbonReductionPct: x.EstimatedCarbonReductionPct, CarbonReductionKg: x.CarbonReductionKgMonth, CostImpact: x.EstimatedCostImpact,
		CostBasis: x.CostBasis, Confidence: x.Confidence, Compliance: cc, Status: domain.Status(x.Status), DecidedBy: x.DecidedBy,
		DecidedAt: x.DecidedAt, AppliedAt: x.AppliedAt, CreatedAt: x.CreatedAt}, nil
}

func (r Postgres) Insert(ctx context.Context, tenantID string, rec domain.Recommendation) (bool, error) {
	cc, err := json.Marshal(rec.Compliance)
	if err != nil {
		return false, err
	}
	created := false
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		id, err := db.New(tx).InsertRecommendation(ctx, db.InsertRecommendationParams{TenantID: tenantID, ProjectID: rec.ProjectID, Type: string(rec.Type),
			Title: rec.Title, Provider: rec.Provider, ServiceName: rec.ServiceName, CurrentRegion: rec.CurrentRegion, RecommendedRegion: rec.RecommendedRegion,
			EstimatedCarbonReductionPct: rec.CarbonReductionPct, CarbonReductionKgMonth: rec.CarbonReductionKg, EstimatedCostImpact: rec.CostImpact,
			CostBasis: rec.CostBasis, Confidence: rec.Confidence, ComplianceCheck: cc, Fingerprint: rec.Fingerprint})
		if database.IsNotFound(err) {
			return nil // same finding already exists
		}
		if err != nil {
			return err
		}
		created = true
		return audit.Record(audit.WithTenant(ctx, tenantID), tx, "recommendation.created", "recommendation:"+id, map[string]any{"type": rec.Type})
	})
	return created, err
}

func (r Postgres) List(ctx context.Context, tenantID, status string, project *string, limit int) ([]domain.Recommendation, error) {
	out := []domain.Recommendation{}
	err := database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		rows, err := db.New(tx).ListRecommendations(ctx, db.ListRecommendationsParams{TenantID: tenantID, Status: status, ProjectID: project, RowLimit: int32(limit)}) //nolint:gosec // limit clamped by handler
		if err != nil {
			return err
		}
		for _, x := range rows {
			d, err := toDomain(x)
			if err != nil {
				return err
			}
			out = append(out, d)
		}
		return nil
	})
	return out, err
}

func (r Postgres) Get(ctx context.Context, tenantID, id string) (rec domain.Recommendation, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		x, err := db.New(tx).GetRecommendation(ctx, db.GetRecommendationParams{TenantID: tenantID, ID: id})
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		if err != nil {
			return err
		}
		rec, err = toDomain(x)
		return err
	})
	return
}

func (r Postgres) Transition(ctx context.Context, tenantID, id string, to domain.Status, actor string, check func(*domain.Recommendation) error) (rec domain.Recommendation, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		x, err := q.GetRecommendation(ctx, db.GetRecommendationParams{TenantID: tenantID, ID: id}) // FOR UPDATE: serializes concurrent decisions
		if database.IsNotFound(err) {
			return domain.ErrNotFound
		}
		if err != nil {
			return err
		}
		if rec, err = toDomain(x); err != nil {
			return err
		}
		if err := rec.Transition(to); err != nil {
			return err
		}
		if check != nil {
			if err := check(&rec); err != nil {
				return err
			}
		}
		if err := q.SetRecommendationStatus(ctx, db.SetRecommendationStatusParams{TenantID: tenantID, ID: id, Status: string(to), DecidedBy: &actor}); err != nil {
			return err
		}
		return audit.Record(ctx, tx, "recommendation."+string(to), "recommendation:"+id, map[string]any{"type": rec.Type, "carbon_kg_month": rec.CarbonReductionKg})
	})
	return
}

func (r Postgres) Workloads(ctx context.Context, tenantID, projectID string, from, to time.Time) (ws []domain.Workload, days int, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		q := db.New(tx)
		carbonRows, err := q.WorkloadsByRegion(ctx, db.WorkloadsByRegionParams{TenantID: tenantID, ProjectID: projectID, MethodologyVersion: methodology.Version, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		costRows, err := q.WorkloadCost(ctx, db.WorkloadCostParams{TenantID: tenantID, ProjectID: projectID, FromTs: from, ToTs: to})
		if err != nil {
			return err
		}
		cost := map[[3]string]float64{}
		for _, c := range costRows {
			cost[[3]string{c.Provider, c.ServiceName, c.RegionID}] = c.Cost
		}
		for _, c := range carbonRows {
			ws = append(ws, domain.Workload{Provider: c.Provider, Service: c.ServiceName, Region: c.RegionID, EnergyKWh: c.EnergyKwh, CarbonKg: c.CarbonKg,
				Cost: cost[[3]string{c.Provider, c.ServiceName, c.RegionID}]})
		}
		n, err := q.WorkloadDays(ctx, db.WorkloadDaysParams{TenantID: tenantID, ProjectID: projectID, MethodologyVersion: methodology.Version, FromTs: from, ToTs: to})
		days = int(n)
		return err
	})
	return
}

func (r Postgres) Intensities(ctx context.Context) (map[string]float64, error) {
	rows, err := db.New(r.Pool).LatestIntensities(ctx)
	m := make(map[string]float64, len(rows))
	for _, x := range rows {
		m[x.RegionID] = x.GPerKwh
	}
	return m, err
}

func (r Postgres) PriceIndex(ctx context.Context, provider string) (map[string]float64, error) {
	rows, err := db.New(r.Pool).PriceIndex(ctx, provider)
	m := make(map[string]float64, len(rows))
	for _, x := range rows {
		m[x.RegionID] = x.Idx
	}
	return m, err
}

func (r Postgres) AllowedRegions(ctx context.Context, tenantID, projectID string) (regions []string, err error) {
	err = database.WithTenantTx(ctx, r.Pool, tenantID, func(tx pgx.Tx) error {
		regions, err = db.New(tx).GetPolicyRegions(ctx, db.GetPolicyRegionsParams{TenantID: tenantID, ProjectID: projectID})
		if database.IsNotFound(err) {
			regions, err = nil, nil // no policy: residency unknown
		}
		return err
	})
	return
}
