// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const getPolicyRegions = `-- name: GetPolicyRegions :one
SELECT allowed_regions FROM projects.policies WHERE tenant_id = $1 AND project_id = $2
`

type GetPolicyRegionsParams struct {
	TenantID  string `json:"tenant_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetPolicyRegions(ctx context.Context, arg GetPolicyRegionsParams) ([]string, error) {
	row := q.db.QueryRow(ctx, getPolicyRegions, arg.TenantID, arg.ProjectID)
	var allowed_regions []string
	err := row.Scan(&allowed_regions)
	return allowed_regions, err
}

const getRecommendation = `-- name: GetRecommendation :one
SELECT id, tenant_id, project_id, type, title, provider, service_name, current_region, recommended_region, estimated_carbon_reduction_pct, carbon_reduction_kg_month, estimated_cost_impact, cost_basis, confidence, compliance_check, status, fingerprint, decided_by, decided_at, applied_at, created_at FROM recommendations.recommendations WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetRecommendationParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetRecommendation(ctx context.Context, arg GetRecommendationParams) (RecommendationsRecommendation, error) {
	row := q.db.QueryRow(ctx, getRecommendation, arg.TenantID, arg.ID)
	var i RecommendationsRecommendation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Provider,
		&i.ServiceName,
		&i.CurrentRegion,
		&i.RecommendedRegion,
		&i.EstimatedCarbonReductionPct,
		&i.CarbonReductionKgMonth,
		&i.EstimatedCostImpact,
		&i.CostBasis,
		&i.Confidence,
		&i.ComplianceCheck,
		&i.Status,
		&i.Fingerprint,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.AppliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecommendation = `-- name: InsertRecommendation :one
INSERT INTO recommendations.recommendations (tenant_id, project_id, type, title, provider, service_name, current_region, recommended_region,
    estimated_carbon_reduction_pct, carbon_reduction_kg_month, estimated_cost_impact, cost_basis, confidence, compliance_check, fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15)
ON CONFLICT (tenant_id, fingerprint) DO NOTHING
RETURNING id
`

type InsertRecommendationParams struct {
	TenantID                    string          `json:"tenant_id"`
	ProjectID                   string          `json:"project_id"`
	Type                        string          `json:"type"`
	Title                       string          `json:"title"`
	Provider                    string          `json:"provider"`
	ServiceName                 string          `json:"service_name"`
	CurrentRegion               string          `json:"current_region"`
	RecommendedRegion           string          `json:"recommended_region"`
	EstimatedCarbonReductionPct float64         `json:"estimated_carbon_reduction_pct"`
	CarbonReductionKgMonth      float64         `json:"carbon_reduction_kg_month"`
	EstimatedCostImpact         *float64        `json:"estimated_cost_impact"`
	CostBasis                   string          `json:"cost_basis"`
	Confidence                  float64         `json:"confidence"`
	ComplianceCheck             json.RawMessage `json:"compliance_check"`
	Fingerprint                 string          `json:"fingerprint"`
}

func (q *Queries) InsertRecommendation(ctx context.Context, arg InsertRecommendationParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRecommendation,
		arg.TenantID,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Provider,
		arg.ServiceName,
		arg.CurrentRegion,
		arg.RecommendedRegion,
		arg.EstimatedCarbonReductionPct,
		arg.CarbonReductionKgMonth,
		arg.EstimatedCostImpact,
		arg.CostBasis,
		arg.Confidence,
		arg.ComplianceCheck,
		arg.Fingerprint,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const latestIntensities = `-- name: LatestIntensities :many
SELECT DISTINCT ON (region_id) region_id, g_co2e_per_kwh::float8 AS g_per_kwh, ts
FROM carbon.grid_intensity WHERE NOT is_forecast ORDER BY region_id, ts DESC
`

type LatestIntensitiesRow struct {
	RegionID string    `json:"region_id"`
	GPerKwh  float64   `json:"g_per_kwh"`
	Ts       time.Time `json:"ts"`
}

func (q *Queries) LatestIntensities(ctx context.Context) ([]LatestIntensitiesRow, error) {
	rows, err := q.db.Query(ctx, latestIntensities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestIntensitiesRow{}
	for rows.Next() {
		var i LatestIntensitiesRow
		if err := rows.Scan(&i.RegionID, &i.GPerKwh, &i.Ts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendations = `-- name: ListRecommendations :many
SELECT id, tenant_id, project_id, type, title, provider, service_name, current_region, recommended_region, estimated_carbon_reduction_pct, carbon_reduction_kg_month, estimated_cost_impact, cost_basis, confidence, compliance_check, status, fingerprint, decided_by, decided_at, applied_at, created_at FROM recommendations.recommendations
WHERE tenant_id = $1 AND ($2::text = '' OR status = $2::text)
  AND ($3::uuid IS NULL OR project_id = $3)
ORDER BY carbon_reduction_kg_month DESC, created_at DESC LIMIT $4
`

type ListRecommendationsParams struct {
	TenantID  string  `json:"tenant_id"`
	Status    string  `json:"status"`
	ProjectID *string `json:"project_id"`
	RowLimit  int32   `json:"row_limit"`
}

func (q *Queries) ListRecommendations(ctx context.Context, arg ListRecommendationsParams) ([]RecommendationsRecommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendations,
		arg.TenantID,
		arg.Status,
		arg.ProjectID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecommendationsRecommendation{}
	for rows.Next() {
		var i RecommendationsRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Provider,
			&i.ServiceName,
			&i.CurrentRegion,
			&i.RecommendedRegion,
			&i.EstimatedCarbonReductionPct,
			&i.CarbonReductionKgMonth,
			&i.EstimatedCostImpact,
			&i.CostBasis,
			&i.Confidence,
			&i.ComplianceCheck,
			&i.Status,
			&i.Fingerprint,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.AppliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priceIndex = `-- name: PriceIndex :many
SELECT region_id, idx::float8 AS idx FROM finops.region_price_index WHERE provider = $1
`

type PriceIndexRow struct {
	RegionID string  `json:"region_id"`
	Idx      float64 `json:"idx"`
}

func (q *Queries) PriceIndex(ctx context.Context, provider string) ([]PriceIndexRow, error) {
	rows, err := q.db.Query(ctx, priceIndex, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceIndexRow{}
	for rows.Next() {
		var i PriceIndexRow
		if err := rows.Scan(&i.RegionID, &i.Idx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecommendationStatus = `-- name: SetRecommendationStatus :exec
UPDATE recommendations.recommendations
SET status = $1, decided_by = $2, decided_at = now(),
    applied_at = CASE WHEN $1::text = 'applied' THEN now() ELSE applied_at END
WHERE tenant_id = $3 AND id = $4
`

type SetRecommendationStatusParams struct {
	Status    string  `json:"status"`
	DecidedBy *string `json:"decided_by"`
	TenantID  string  `json:"tenant_id"`
	ID        string  `json:"id"`
}

func (q *Queries) SetRecommendationStatus(ctx context.Context, arg SetRecommendationStatusParams) error {
	_, err := q.db.Exec(ctx, setRecommendationStatus,
		arg.Status,
		arg.DecidedBy,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const workloadCost = `-- name: WorkloadCost :many
SELECT provider, service_name, region_id, sum(billed_cost)::float8 AS cost
FROM usage.usage_records
WHERE tenant_id = $1 AND project_id = $2
  AND recorded_at >= $3 AND recorded_at < $4
GROUP BY provider, service_name, region_id
`

type WorkloadCostParams struct {
	TenantID  string    `json:"tenant_id"`
	ProjectID string    `json:"project_id"`
	FromTs    time.Time `json:"from_ts"`
	ToTs      time.Time `json:"to_ts"`
}

type WorkloadCostRow struct {
	Provider    string  `json:"provider"`
	ServiceName string  `json:"service_name"`
	RegionID    string  `json:"region_id"`
	Cost        float64 `json:"cost"`
}

func (q *Queries) WorkloadCost(ctx context.Context, arg WorkloadCostParams) ([]WorkloadCostRow, error) {
	rows, err := q.db.Query(ctx, workloadCost,
		arg.TenantID,
		arg.ProjectID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadCostRow{}
	for rows.Next() {
		var i WorkloadCostRow
		if err := rows.Scan(
			&i.Provider,
			&i.ServiceName,
			&i.RegionID,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workloadDays = `-- name: WorkloadDays :one
SELECT count(DISTINCT date_trunc('day', period_start))::int AS days FROM carbon.calculations
WHERE tenant_id = $1 AND project_id = $2 AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
`

type WorkloadDaysParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          string    `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

func (q *Queries) WorkloadDays(ctx context.Context, arg WorkloadDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, workloadDays,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	var days int32
	err := row.Scan(&days)
	return days, err
}

const workloadsByRegion = `-- name: WorkloadsByRegion :many
SELECT provider, service_name, region_id,
       sum(energy_kwh)::float8 AS energy_kwh, sum(carbon_kg_co2e)::float8 AS carbon_kg
FROM carbon.calculations
WHERE tenant_id = $1 AND project_id = $2 AND methodology_version = $3
  AND period_start >= $4 AND period_start < $5
GROUP BY provider, service_name, region_id
`

type WorkloadsByRegionParams struct {
	TenantID           string    `json:"tenant_id"`
	ProjectID          string    `json:"project_id"`
	MethodologyVersion string    `json:"methodology_version"`
	FromTs             time.Time `json:"from_ts"`
	ToTs               time.Time `json:"to_ts"`
}

type WorkloadsByRegionRow struct {
	Provider    string  `json:"provider"`
	ServiceName string  `json:"service_name"`
	RegionID    string  `json:"region_id"`
	EnergyKwh   float64 `json:"energy_kwh"`
	CarbonKg    float64 `json:"carbon_kg"`
}

// Input of the region_shift generator: last-window carbon per workload (read-only view of the carbon schema).
func (q *Queries) WorkloadsByRegion(ctx context.Context, arg WorkloadsByRegionParams) ([]WorkloadsByRegionRow, error) {
	rows, err := q.db.Query(ctx, workloadsByRegion,
		arg.TenantID,
		arg.ProjectID,
		arg.MethodologyVersion,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadsByRegionRow{}
	for rows.Next() {
		var i WorkloadsByRegionRow
		if err := rows.Scan(
			&i.Provider,
			&i.ServiceName,
			&i.RegionID,
			&i.EnergyKwh,
			&i.CarbonKg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
